/*
Treasury Management API

Testing ConfigureExceptionalWorkingDayAPIService

*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech);

package openapi

import (
	"context"
	"github.com/stretchr/testify/assert"
	"github.com/stretchr/testify/require"
	"testing"
	openapiclient "github.com/GIT_USER_ID/GIT_REPO_ID"
)

func Test_openapi_ConfigureExceptionalWorkingDayAPIService(t *testing.T) {

	configuration := openapiclient.NewConfiguration()
	apiClient := openapiclient.NewAPIClient(configuration)

	t.Run("Test ConfigureExceptionalWorkingDayAPIService OfficesOfficeIdExceptionalWorkingDaysDelete", func(t *testing.T) {

		t.Skip("skip test")  // remove to run test

		var officeId string

		resp, httpRes, err := apiClient.ConfigureExceptionalWorkingDayAPI.OfficesOfficeIdExceptionalWorkingDaysDelete(context.Background(), officeId).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test ConfigureExceptionalWorkingDayAPIService OfficesOfficeIdExceptionalWorkingDaysGet", func(t *testing.T) {

		t.Skip("skip test")  // remove to run test

		var officeId string

		resp, httpRes, err := apiClient.ConfigureExceptionalWorkingDayAPI.OfficesOfficeIdExceptionalWorkingDaysGet(context.Background(), officeId).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test ConfigureExceptionalWorkingDayAPIService OfficesOfficeIdExceptionalWorkingDaysPost", func(t *testing.T) {

		t.Skip("skip test")  // remove to run test

		var officeId int32

		resp, httpRes, err := apiClient.ConfigureExceptionalWorkingDayAPI.OfficesOfficeIdExceptionalWorkingDaysPost(context.Background(), officeId).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

}
