/*
Treasury Management API

Testing ConfigureStampsWriteOffLimitsAPIService

*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech);

package openapi

import (
	"context"
	"github.com/stretchr/testify/assert"
	"github.com/stretchr/testify/require"
	"testing"
	openapiclient "github.com/GIT_USER_ID/GIT_REPO_ID"
)

func Test_openapi_ConfigureStampsWriteOffLimitsAPIService(t *testing.T) {

	configuration := openapiclient.NewConfiguration()
	apiClient := openapiclient.NewAPIClient(configuration)

	t.Run("Test ConfigureStampsWriteOffLimitsAPIService SoiledWriteOffLimitsGet", func(t *testing.T) {

		t.Skip("skip test")  // remove to run test

		resp, httpRes, err := apiClient.ConfigureStampsWriteOffLimitsAPI.SoiledWriteOffLimitsGet(context.Background()).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test ConfigureStampsWriteOffLimitsAPIService SoiledWriteOffLimitsLimitIdDelete", func(t *testing.T) {

		t.Skip("skip test")  // remove to run test

		var limitId string

		resp, httpRes, err := apiClient.ConfigureStampsWriteOffLimitsAPI.SoiledWriteOffLimitsLimitIdDelete(context.Background(), limitId).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test ConfigureStampsWriteOffLimitsAPIService SoiledWriteOffLimitsPost", func(t *testing.T) {

		t.Skip("skip test")  // remove to run test

		resp, httpRes, err := apiClient.ConfigureStampsWriteOffLimitsAPI.SoiledWriteOffLimitsPost(context.Background()).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

}
