/*
Treasury Management API

A comprehensive API for managing addresses, offering endpoints for creation, update, deletion, and retrieval of address data.

API version: 1.0
Contact: support_cept@indiapost.gov.in
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
)

// checks if the ResponseDeleteExceptionalWkgDayAPIResponse type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &ResponseDeleteExceptionalWkgDayAPIResponse{}

// ResponseDeleteExceptionalWkgDayAPIResponse struct for ResponseDeleteExceptionalWkgDayAPIResponse
type ResponseDeleteExceptionalWkgDayAPIResponse struct {
	Message *string `json:"message,omitempty"`
	StatusCode *int32 `json:"status_code,omitempty"`
}

// NewResponseDeleteExceptionalWkgDayAPIResponse instantiates a new ResponseDeleteExceptionalWkgDayAPIResponse object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewResponseDeleteExceptionalWkgDayAPIResponse() *ResponseDeleteExceptionalWkgDayAPIResponse {
	this := ResponseDeleteExceptionalWkgDayAPIResponse{}
	return &this
}

// NewResponseDeleteExceptionalWkgDayAPIResponseWithDefaults instantiates a new ResponseDeleteExceptionalWkgDayAPIResponse object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewResponseDeleteExceptionalWkgDayAPIResponseWithDefaults() *ResponseDeleteExceptionalWkgDayAPIResponse {
	this := ResponseDeleteExceptionalWkgDayAPIResponse{}
	return &this
}

// GetMessage returns the Message field value if set, zero value otherwise.
func (o *ResponseDeleteExceptionalWkgDayAPIResponse) GetMessage() string {
	if o == nil || IsNil(o.Message) {
		var ret string
		return ret
	}
	return *o.Message
}

// GetMessageOk returns a tuple with the Message field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ResponseDeleteExceptionalWkgDayAPIResponse) GetMessageOk() (*string, bool) {
	if o == nil || IsNil(o.Message) {
		return nil, false
	}
	return o.Message, true
}

// HasMessage returns a boolean if a field has been set.
func (o *ResponseDeleteExceptionalWkgDayAPIResponse) HasMessage() bool {
	if o != nil && !IsNil(o.Message) {
		return true
	}

	return false
}

// SetMessage gets a reference to the given string and assigns it to the Message field.
func (o *ResponseDeleteExceptionalWkgDayAPIResponse) SetMessage(v string) {
	o.Message = &v
}

// GetStatusCode returns the StatusCode field value if set, zero value otherwise.
func (o *ResponseDeleteExceptionalWkgDayAPIResponse) GetStatusCode() int32 {
	if o == nil || IsNil(o.StatusCode) {
		var ret int32
		return ret
	}
	return *o.StatusCode
}

// GetStatusCodeOk returns a tuple with the StatusCode field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ResponseDeleteExceptionalWkgDayAPIResponse) GetStatusCodeOk() (*int32, bool) {
	if o == nil || IsNil(o.StatusCode) {
		return nil, false
	}
	return o.StatusCode, true
}

// HasStatusCode returns a boolean if a field has been set.
func (o *ResponseDeleteExceptionalWkgDayAPIResponse) HasStatusCode() bool {
	if o != nil && !IsNil(o.StatusCode) {
		return true
	}

	return false
}

// SetStatusCode gets a reference to the given int32 and assigns it to the StatusCode field.
func (o *ResponseDeleteExceptionalWkgDayAPIResponse) SetStatusCode(v int32) {
	o.StatusCode = &v
}

func (o ResponseDeleteExceptionalWkgDayAPIResponse) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o ResponseDeleteExceptionalWkgDayAPIResponse) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Message) {
		toSerialize["message"] = o.Message
	}
	if !IsNil(o.StatusCode) {
		toSerialize["status_code"] = o.StatusCode
	}
	return toSerialize, nil
}

type NullableResponseDeleteExceptionalWkgDayAPIResponse struct {
	value *ResponseDeleteExceptionalWkgDayAPIResponse
	isSet bool
}

func (v NullableResponseDeleteExceptionalWkgDayAPIResponse) Get() *ResponseDeleteExceptionalWkgDayAPIResponse {
	return v.value
}

func (v *NullableResponseDeleteExceptionalWkgDayAPIResponse) Set(val *ResponseDeleteExceptionalWkgDayAPIResponse) {
	v.value = val
	v.isSet = true
}

func (v NullableResponseDeleteExceptionalWkgDayAPIResponse) IsSet() bool {
	return v.isSet
}

func (v *NullableResponseDeleteExceptionalWkgDayAPIResponse) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableResponseDeleteExceptionalWkgDayAPIResponse(val *ResponseDeleteExceptionalWkgDayAPIResponse) *NullableResponseDeleteExceptionalWkgDayAPIResponse {
	return &NullableResponseDeleteExceptionalWkgDayAPIResponse{value: val, isSet: true}
}

func (v NullableResponseDeleteExceptionalWkgDayAPIResponse) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableResponseDeleteExceptionalWkgDayAPIResponse) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


