/*
Treasury Management API

A comprehensive API for managing addresses, offering endpoints for creation, update, deletion, and retrieval of address data.

API version: 1.0
Contact: support_cept@indiapost.gov.in
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
)

// checks if the ResponseCreateCurrenciesResponse type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &ResponseCreateCurrenciesResponse{}

// ResponseCreateCurrenciesResponse struct for ResponseCreateCurrenciesResponse
type ResponseCreateCurrenciesResponse struct {
	CurrencyId *string `json:"currency_id,omitempty"`
}

// NewResponseCreateCurrenciesResponse instantiates a new ResponseCreateCurrenciesResponse object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewResponseCreateCurrenciesResponse() *ResponseCreateCurrenciesResponse {
	this := ResponseCreateCurrenciesResponse{}
	return &this
}

// NewResponseCreateCurrenciesResponseWithDefaults instantiates a new ResponseCreateCurrenciesResponse object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewResponseCreateCurrenciesResponseWithDefaults() *ResponseCreateCurrenciesResponse {
	this := ResponseCreateCurrenciesResponse{}
	return &this
}

// GetCurrencyId returns the CurrencyId field value if set, zero value otherwise.
func (o *ResponseCreateCurrenciesResponse) GetCurrencyId() string {
	if o == nil || IsNil(o.CurrencyId) {
		var ret string
		return ret
	}
	return *o.CurrencyId
}

// GetCurrencyIdOk returns a tuple with the CurrencyId field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ResponseCreateCurrenciesResponse) GetCurrencyIdOk() (*string, bool) {
	if o == nil || IsNil(o.CurrencyId) {
		return nil, false
	}
	return o.CurrencyId, true
}

// HasCurrencyId returns a boolean if a field has been set.
func (o *ResponseCreateCurrenciesResponse) HasCurrencyId() bool {
	if o != nil && !IsNil(o.CurrencyId) {
		return true
	}

	return false
}

// SetCurrencyId gets a reference to the given string and assigns it to the CurrencyId field.
func (o *ResponseCreateCurrenciesResponse) SetCurrencyId(v string) {
	o.CurrencyId = &v
}

func (o ResponseCreateCurrenciesResponse) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o ResponseCreateCurrenciesResponse) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.CurrencyId) {
		toSerialize["currency_id"] = o.CurrencyId
	}
	return toSerialize, nil
}

type NullableResponseCreateCurrenciesResponse struct {
	value *ResponseCreateCurrenciesResponse
	isSet bool
}

func (v NullableResponseCreateCurrenciesResponse) Get() *ResponseCreateCurrenciesResponse {
	return v.value
}

func (v *NullableResponseCreateCurrenciesResponse) Set(val *ResponseCreateCurrenciesResponse) {
	v.value = val
	v.isSet = true
}

func (v NullableResponseCreateCurrenciesResponse) IsSet() bool {
	return v.isSet
}

func (v *NullableResponseCreateCurrenciesResponse) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableResponseCreateCurrenciesResponse(val *ResponseCreateCurrenciesResponse) *NullableResponseCreateCurrenciesResponse {
	return &NullableResponseCreateCurrenciesResponse{value: val, isSet: true}
}

func (v NullableResponseCreateCurrenciesResponse) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableResponseCreateCurrenciesResponse) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


