/*
Treasury Management API

A comprehensive API for managing addresses, offering endpoints for creation, update, deletion, and retrieval of address data.

API version: 1.0
Contact: support_cept@indiapost.gov.in
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
)

// checks if the ResponseUpdateStampSoiledApiResponse type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &ResponseUpdateStampSoiledApiResponse{}

// ResponseUpdateStampSoiledApiResponse struct for ResponseUpdateStampSoiledApiResponse
type ResponseUpdateStampSoiledApiResponse struct {
	Message *string `json:"message,omitempty"`
	StatusCode *int32 `json:"status_code,omitempty"`
}

// NewResponseUpdateStampSoiledApiResponse instantiates a new ResponseUpdateStampSoiledApiResponse object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewResponseUpdateStampSoiledApiResponse() *ResponseUpdateStampSoiledApiResponse {
	this := ResponseUpdateStampSoiledApiResponse{}
	return &this
}

// NewResponseUpdateStampSoiledApiResponseWithDefaults instantiates a new ResponseUpdateStampSoiledApiResponse object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewResponseUpdateStampSoiledApiResponseWithDefaults() *ResponseUpdateStampSoiledApiResponse {
	this := ResponseUpdateStampSoiledApiResponse{}
	return &this
}

// GetMessage returns the Message field value if set, zero value otherwise.
func (o *ResponseUpdateStampSoiledApiResponse) GetMessage() string {
	if o == nil || IsNil(o.Message) {
		var ret string
		return ret
	}
	return *o.Message
}

// GetMessageOk returns a tuple with the Message field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ResponseUpdateStampSoiledApiResponse) GetMessageOk() (*string, bool) {
	if o == nil || IsNil(o.Message) {
		return nil, false
	}
	return o.Message, true
}

// HasMessage returns a boolean if a field has been set.
func (o *ResponseUpdateStampSoiledApiResponse) HasMessage() bool {
	if o != nil && !IsNil(o.Message) {
		return true
	}

	return false
}

// SetMessage gets a reference to the given string and assigns it to the Message field.
func (o *ResponseUpdateStampSoiledApiResponse) SetMessage(v string) {
	o.Message = &v
}

// GetStatusCode returns the StatusCode field value if set, zero value otherwise.
func (o *ResponseUpdateStampSoiledApiResponse) GetStatusCode() int32 {
	if o == nil || IsNil(o.StatusCode) {
		var ret int32
		return ret
	}
	return *o.StatusCode
}

// GetStatusCodeOk returns a tuple with the StatusCode field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ResponseUpdateStampSoiledApiResponse) GetStatusCodeOk() (*int32, bool) {
	if o == nil || IsNil(o.StatusCode) {
		return nil, false
	}
	return o.StatusCode, true
}

// HasStatusCode returns a boolean if a field has been set.
func (o *ResponseUpdateStampSoiledApiResponse) HasStatusCode() bool {
	if o != nil && !IsNil(o.StatusCode) {
		return true
	}

	return false
}

// SetStatusCode gets a reference to the given int32 and assigns it to the StatusCode field.
func (o *ResponseUpdateStampSoiledApiResponse) SetStatusCode(v int32) {
	o.StatusCode = &v
}

func (o ResponseUpdateStampSoiledApiResponse) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o ResponseUpdateStampSoiledApiResponse) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Message) {
		toSerialize["message"] = o.Message
	}
	if !IsNil(o.StatusCode) {
		toSerialize["status_code"] = o.StatusCode
	}
	return toSerialize, nil
}

type NullableResponseUpdateStampSoiledApiResponse struct {
	value *ResponseUpdateStampSoiledApiResponse
	isSet bool
}

func (v NullableResponseUpdateStampSoiledApiResponse) Get() *ResponseUpdateStampSoiledApiResponse {
	return v.value
}

func (v *NullableResponseUpdateStampSoiledApiResponse) Set(val *ResponseUpdateStampSoiledApiResponse) {
	v.value = val
	v.isSet = true
}

func (v NullableResponseUpdateStampSoiledApiResponse) IsSet() bool {
	return v.isSet
}

func (v *NullableResponseUpdateStampSoiledApiResponse) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableResponseUpdateStampSoiledApiResponse(val *ResponseUpdateStampSoiledApiResponse) *NullableResponseUpdateStampSoiledApiResponse {
	return &NullableResponseUpdateStampSoiledApiResponse{value: val, isSet: true}
}

func (v NullableResponseUpdateStampSoiledApiResponse) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableResponseUpdateStampSoiledApiResponse) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


