/*
Treasury Management API

A comprehensive API for managing addresses, offering endpoints for creation, update, deletion, and retrieval of address data.

API version: 1.0
Contact: support_cept@indiapost.gov.in
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
)

// checks if the ResponseChequesInTransit type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &ResponseChequesInTransit{}

// ResponseChequesInTransit struct for ResponseChequesInTransit
type ResponseChequesInTransit struct {
	ChequeAmount *float32 `json:"cheque_amount,omitempty"`
	ChequeDate *string `json:"cheque_date,omitempty"`
	ChequeNo *string `json:"cheque_no,omitempty"`
	FromOffice *string `json:"from_office,omitempty"`
	FromUnitId *int32 `json:"from_unit_id,omitempty"`
	IsRsao *bool `json:"is_rsao,omitempty"`
	ToOffice *string `json:"to_office,omitempty"`
	ToUnitId *int32 `json:"to_unit_id,omitempty"`
	TransDate *string `json:"trans_date,omitempty"`
	TransId *string `json:"trans_id,omitempty"`
	TransactionDate *string `json:"transaction_date,omitempty"`
}

// NewResponseChequesInTransit instantiates a new ResponseChequesInTransit object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewResponseChequesInTransit() *ResponseChequesInTransit {
	this := ResponseChequesInTransit{}
	return &this
}

// NewResponseChequesInTransitWithDefaults instantiates a new ResponseChequesInTransit object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewResponseChequesInTransitWithDefaults() *ResponseChequesInTransit {
	this := ResponseChequesInTransit{}
	return &this
}

// GetChequeAmount returns the ChequeAmount field value if set, zero value otherwise.
func (o *ResponseChequesInTransit) GetChequeAmount() float32 {
	if o == nil || IsNil(o.ChequeAmount) {
		var ret float32
		return ret
	}
	return *o.ChequeAmount
}

// GetChequeAmountOk returns a tuple with the ChequeAmount field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ResponseChequesInTransit) GetChequeAmountOk() (*float32, bool) {
	if o == nil || IsNil(o.ChequeAmount) {
		return nil, false
	}
	return o.ChequeAmount, true
}

// HasChequeAmount returns a boolean if a field has been set.
func (o *ResponseChequesInTransit) HasChequeAmount() bool {
	if o != nil && !IsNil(o.ChequeAmount) {
		return true
	}

	return false
}

// SetChequeAmount gets a reference to the given float32 and assigns it to the ChequeAmount field.
func (o *ResponseChequesInTransit) SetChequeAmount(v float32) {
	o.ChequeAmount = &v
}

// GetChequeDate returns the ChequeDate field value if set, zero value otherwise.
func (o *ResponseChequesInTransit) GetChequeDate() string {
	if o == nil || IsNil(o.ChequeDate) {
		var ret string
		return ret
	}
	return *o.ChequeDate
}

// GetChequeDateOk returns a tuple with the ChequeDate field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ResponseChequesInTransit) GetChequeDateOk() (*string, bool) {
	if o == nil || IsNil(o.ChequeDate) {
		return nil, false
	}
	return o.ChequeDate, true
}

// HasChequeDate returns a boolean if a field has been set.
func (o *ResponseChequesInTransit) HasChequeDate() bool {
	if o != nil && !IsNil(o.ChequeDate) {
		return true
	}

	return false
}

// SetChequeDate gets a reference to the given string and assigns it to the ChequeDate field.
func (o *ResponseChequesInTransit) SetChequeDate(v string) {
	o.ChequeDate = &v
}

// GetChequeNo returns the ChequeNo field value if set, zero value otherwise.
func (o *ResponseChequesInTransit) GetChequeNo() string {
	if o == nil || IsNil(o.ChequeNo) {
		var ret string
		return ret
	}
	return *o.ChequeNo
}

// GetChequeNoOk returns a tuple with the ChequeNo field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ResponseChequesInTransit) GetChequeNoOk() (*string, bool) {
	if o == nil || IsNil(o.ChequeNo) {
		return nil, false
	}
	return o.ChequeNo, true
}

// HasChequeNo returns a boolean if a field has been set.
func (o *ResponseChequesInTransit) HasChequeNo() bool {
	if o != nil && !IsNil(o.ChequeNo) {
		return true
	}

	return false
}

// SetChequeNo gets a reference to the given string and assigns it to the ChequeNo field.
func (o *ResponseChequesInTransit) SetChequeNo(v string) {
	o.ChequeNo = &v
}

// GetFromOffice returns the FromOffice field value if set, zero value otherwise.
func (o *ResponseChequesInTransit) GetFromOffice() string {
	if o == nil || IsNil(o.FromOffice) {
		var ret string
		return ret
	}
	return *o.FromOffice
}

// GetFromOfficeOk returns a tuple with the FromOffice field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ResponseChequesInTransit) GetFromOfficeOk() (*string, bool) {
	if o == nil || IsNil(o.FromOffice) {
		return nil, false
	}
	return o.FromOffice, true
}

// HasFromOffice returns a boolean if a field has been set.
func (o *ResponseChequesInTransit) HasFromOffice() bool {
	if o != nil && !IsNil(o.FromOffice) {
		return true
	}

	return false
}

// SetFromOffice gets a reference to the given string and assigns it to the FromOffice field.
func (o *ResponseChequesInTransit) SetFromOffice(v string) {
	o.FromOffice = &v
}

// GetFromUnitId returns the FromUnitId field value if set, zero value otherwise.
func (o *ResponseChequesInTransit) GetFromUnitId() int32 {
	if o == nil || IsNil(o.FromUnitId) {
		var ret int32
		return ret
	}
	return *o.FromUnitId
}

// GetFromUnitIdOk returns a tuple with the FromUnitId field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ResponseChequesInTransit) GetFromUnitIdOk() (*int32, bool) {
	if o == nil || IsNil(o.FromUnitId) {
		return nil, false
	}
	return o.FromUnitId, true
}

// HasFromUnitId returns a boolean if a field has been set.
func (o *ResponseChequesInTransit) HasFromUnitId() bool {
	if o != nil && !IsNil(o.FromUnitId) {
		return true
	}

	return false
}

// SetFromUnitId gets a reference to the given int32 and assigns it to the FromUnitId field.
func (o *ResponseChequesInTransit) SetFromUnitId(v int32) {
	o.FromUnitId = &v
}

// GetIsRsao returns the IsRsao field value if set, zero value otherwise.
func (o *ResponseChequesInTransit) GetIsRsao() bool {
	if o == nil || IsNil(o.IsRsao) {
		var ret bool
		return ret
	}
	return *o.IsRsao
}

// GetIsRsaoOk returns a tuple with the IsRsao field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ResponseChequesInTransit) GetIsRsaoOk() (*bool, bool) {
	if o == nil || IsNil(o.IsRsao) {
		return nil, false
	}
	return o.IsRsao, true
}

// HasIsRsao returns a boolean if a field has been set.
func (o *ResponseChequesInTransit) HasIsRsao() bool {
	if o != nil && !IsNil(o.IsRsao) {
		return true
	}

	return false
}

// SetIsRsao gets a reference to the given bool and assigns it to the IsRsao field.
func (o *ResponseChequesInTransit) SetIsRsao(v bool) {
	o.IsRsao = &v
}

// GetToOffice returns the ToOffice field value if set, zero value otherwise.
func (o *ResponseChequesInTransit) GetToOffice() string {
	if o == nil || IsNil(o.ToOffice) {
		var ret string
		return ret
	}
	return *o.ToOffice
}

// GetToOfficeOk returns a tuple with the ToOffice field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ResponseChequesInTransit) GetToOfficeOk() (*string, bool) {
	if o == nil || IsNil(o.ToOffice) {
		return nil, false
	}
	return o.ToOffice, true
}

// HasToOffice returns a boolean if a field has been set.
func (o *ResponseChequesInTransit) HasToOffice() bool {
	if o != nil && !IsNil(o.ToOffice) {
		return true
	}

	return false
}

// SetToOffice gets a reference to the given string and assigns it to the ToOffice field.
func (o *ResponseChequesInTransit) SetToOffice(v string) {
	o.ToOffice = &v
}

// GetToUnitId returns the ToUnitId field value if set, zero value otherwise.
func (o *ResponseChequesInTransit) GetToUnitId() int32 {
	if o == nil || IsNil(o.ToUnitId) {
		var ret int32
		return ret
	}
	return *o.ToUnitId
}

// GetToUnitIdOk returns a tuple with the ToUnitId field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ResponseChequesInTransit) GetToUnitIdOk() (*int32, bool) {
	if o == nil || IsNil(o.ToUnitId) {
		return nil, false
	}
	return o.ToUnitId, true
}

// HasToUnitId returns a boolean if a field has been set.
func (o *ResponseChequesInTransit) HasToUnitId() bool {
	if o != nil && !IsNil(o.ToUnitId) {
		return true
	}

	return false
}

// SetToUnitId gets a reference to the given int32 and assigns it to the ToUnitId field.
func (o *ResponseChequesInTransit) SetToUnitId(v int32) {
	o.ToUnitId = &v
}

// GetTransDate returns the TransDate field value if set, zero value otherwise.
func (o *ResponseChequesInTransit) GetTransDate() string {
	if o == nil || IsNil(o.TransDate) {
		var ret string
		return ret
	}
	return *o.TransDate
}

// GetTransDateOk returns a tuple with the TransDate field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ResponseChequesInTransit) GetTransDateOk() (*string, bool) {
	if o == nil || IsNil(o.TransDate) {
		return nil, false
	}
	return o.TransDate, true
}

// HasTransDate returns a boolean if a field has been set.
func (o *ResponseChequesInTransit) HasTransDate() bool {
	if o != nil && !IsNil(o.TransDate) {
		return true
	}

	return false
}

// SetTransDate gets a reference to the given string and assigns it to the TransDate field.
func (o *ResponseChequesInTransit) SetTransDate(v string) {
	o.TransDate = &v
}

// GetTransId returns the TransId field value if set, zero value otherwise.
func (o *ResponseChequesInTransit) GetTransId() string {
	if o == nil || IsNil(o.TransId) {
		var ret string
		return ret
	}
	return *o.TransId
}

// GetTransIdOk returns a tuple with the TransId field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ResponseChequesInTransit) GetTransIdOk() (*string, bool) {
	if o == nil || IsNil(o.TransId) {
		return nil, false
	}
	return o.TransId, true
}

// HasTransId returns a boolean if a field has been set.
func (o *ResponseChequesInTransit) HasTransId() bool {
	if o != nil && !IsNil(o.TransId) {
		return true
	}

	return false
}

// SetTransId gets a reference to the given string and assigns it to the TransId field.
func (o *ResponseChequesInTransit) SetTransId(v string) {
	o.TransId = &v
}

// GetTransactionDate returns the TransactionDate field value if set, zero value otherwise.
func (o *ResponseChequesInTransit) GetTransactionDate() string {
	if o == nil || IsNil(o.TransactionDate) {
		var ret string
		return ret
	}
	return *o.TransactionDate
}

// GetTransactionDateOk returns a tuple with the TransactionDate field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ResponseChequesInTransit) GetTransactionDateOk() (*string, bool) {
	if o == nil || IsNil(o.TransactionDate) {
		return nil, false
	}
	return o.TransactionDate, true
}

// HasTransactionDate returns a boolean if a field has been set.
func (o *ResponseChequesInTransit) HasTransactionDate() bool {
	if o != nil && !IsNil(o.TransactionDate) {
		return true
	}

	return false
}

// SetTransactionDate gets a reference to the given string and assigns it to the TransactionDate field.
func (o *ResponseChequesInTransit) SetTransactionDate(v string) {
	o.TransactionDate = &v
}

func (o ResponseChequesInTransit) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o ResponseChequesInTransit) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.ChequeAmount) {
		toSerialize["cheque_amount"] = o.ChequeAmount
	}
	if !IsNil(o.ChequeDate) {
		toSerialize["cheque_date"] = o.ChequeDate
	}
	if !IsNil(o.ChequeNo) {
		toSerialize["cheque_no"] = o.ChequeNo
	}
	if !IsNil(o.FromOffice) {
		toSerialize["from_office"] = o.FromOffice
	}
	if !IsNil(o.FromUnitId) {
		toSerialize["from_unit_id"] = o.FromUnitId
	}
	if !IsNil(o.IsRsao) {
		toSerialize["is_rsao"] = o.IsRsao
	}
	if !IsNil(o.ToOffice) {
		toSerialize["to_office"] = o.ToOffice
	}
	if !IsNil(o.ToUnitId) {
		toSerialize["to_unit_id"] = o.ToUnitId
	}
	if !IsNil(o.TransDate) {
		toSerialize["trans_date"] = o.TransDate
	}
	if !IsNil(o.TransId) {
		toSerialize["trans_id"] = o.TransId
	}
	if !IsNil(o.TransactionDate) {
		toSerialize["transaction_date"] = o.TransactionDate
	}
	return toSerialize, nil
}

type NullableResponseChequesInTransit struct {
	value *ResponseChequesInTransit
	isSet bool
}

func (v NullableResponseChequesInTransit) Get() *ResponseChequesInTransit {
	return v.value
}

func (v *NullableResponseChequesInTransit) Set(val *ResponseChequesInTransit) {
	v.value = val
	v.isSet = true
}

func (v NullableResponseChequesInTransit) IsSet() bool {
	return v.isSet
}

func (v *NullableResponseChequesInTransit) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableResponseChequesInTransit(val *ResponseChequesInTransit) *NullableResponseChequesInTransit {
	return &NullableResponseChequesInTransit{value: val, isSet: true}
}

func (v NullableResponseChequesInTransit) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableResponseChequesInTransit) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


