/*
Treasury Management API

A comprehensive API for managing addresses, offering endpoints for creation, update, deletion, and retrieval of address data.

API version: 1.0
Contact: support_cept@indiapost.gov.in
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
)

// checks if the ResponseIPOBal type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &ResponseIPOBal{}

// ResponseIPOBal struct for ResponseIPOBal
type ResponseIPOBal struct {
	Balance *int32 `json:"balance,omitempty"`
	Denomination *string `json:"denomination,omitempty"`
}

// NewResponseIPOBal instantiates a new ResponseIPOBal object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewResponseIPOBal() *ResponseIPOBal {
	this := ResponseIPOBal{}
	return &this
}

// NewResponseIPOBalWithDefaults instantiates a new ResponseIPOBal object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewResponseIPOBalWithDefaults() *ResponseIPOBal {
	this := ResponseIPOBal{}
	return &this
}

// GetBalance returns the Balance field value if set, zero value otherwise.
func (o *ResponseIPOBal) GetBalance() int32 {
	if o == nil || IsNil(o.Balance) {
		var ret int32
		return ret
	}
	return *o.Balance
}

// GetBalanceOk returns a tuple with the Balance field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ResponseIPOBal) GetBalanceOk() (*int32, bool) {
	if o == nil || IsNil(o.Balance) {
		return nil, false
	}
	return o.Balance, true
}

// HasBalance returns a boolean if a field has been set.
func (o *ResponseIPOBal) HasBalance() bool {
	if o != nil && !IsNil(o.Balance) {
		return true
	}

	return false
}

// SetBalance gets a reference to the given int32 and assigns it to the Balance field.
func (o *ResponseIPOBal) SetBalance(v int32) {
	o.Balance = &v
}

// GetDenomination returns the Denomination field value if set, zero value otherwise.
func (o *ResponseIPOBal) GetDenomination() string {
	if o == nil || IsNil(o.Denomination) {
		var ret string
		return ret
	}
	return *o.Denomination
}

// GetDenominationOk returns a tuple with the Denomination field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ResponseIPOBal) GetDenominationOk() (*string, bool) {
	if o == nil || IsNil(o.Denomination) {
		return nil, false
	}
	return o.Denomination, true
}

// HasDenomination returns a boolean if a field has been set.
func (o *ResponseIPOBal) HasDenomination() bool {
	if o != nil && !IsNil(o.Denomination) {
		return true
	}

	return false
}

// SetDenomination gets a reference to the given string and assigns it to the Denomination field.
func (o *ResponseIPOBal) SetDenomination(v string) {
	o.Denomination = &v
}

func (o ResponseIPOBal) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o ResponseIPOBal) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Balance) {
		toSerialize["balance"] = o.Balance
	}
	if !IsNil(o.Denomination) {
		toSerialize["denomination"] = o.Denomination
	}
	return toSerialize, nil
}

type NullableResponseIPOBal struct {
	value *ResponseIPOBal
	isSet bool
}

func (v NullableResponseIPOBal) Get() *ResponseIPOBal {
	return v.value
}

func (v *NullableResponseIPOBal) Set(val *ResponseIPOBal) {
	v.value = val
	v.isSet = true
}

func (v NullableResponseIPOBal) IsSet() bool {
	return v.isSet
}

func (v *NullableResponseIPOBal) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableResponseIPOBal(val *ResponseIPOBal) *NullableResponseIPOBal {
	return &NullableResponseIPOBal{value: val, isSet: true}
}

func (v NullableResponseIPOBal) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableResponseIPOBal) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


