/*
Treasury Management API

A comprehensive API for managing addresses, offering endpoints for creation, update, deletion, and retrieval of address data.

API version: 1.0
Contact: support_cept@indiapost.gov.in
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
)

// checks if the HandlerTreasuryMiscTransactionResponse type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &HandlerTreasuryMiscTransactionResponse{}

// HandlerTreasuryMiscTransactionResponse struct for HandlerTreasuryMiscTransactionResponse
type HandlerTreasuryMiscTransactionResponse struct {
	AccountDescdetails []HandlerAccountDescdetails `json:"accountDescdetails,omitempty"`
	ApproverDate *string `json:"approver_date,omitempty"`
	ApproverId *int32 `json:"approver_id,omitempty"`
	ApproverRemarks *string `json:"approver_remarks,omitempty"`
	IsApproved *bool `json:"is_approved,omitempty"`
	OfficeId *int32 `json:"office_id,omitempty"`
	Remarks *string `json:"remarks,omitempty"`
	ReqAmount *float32 `json:"req_amount,omitempty"`
	ReqDetails *map[string]float32 `json:"req_details,omitempty"`
	RequestType *string `json:"request_type,omitempty"`
	TransDate *string `json:"trans_date,omitempty"`
	TransactionId *string `json:"transaction_id,omitempty"`
	TxnMode *string `json:"txn_mode,omitempty"`
	UserId *int32 `json:"user_id,omitempty"`
}

// NewHandlerTreasuryMiscTransactionResponse instantiates a new HandlerTreasuryMiscTransactionResponse object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewHandlerTreasuryMiscTransactionResponse() *HandlerTreasuryMiscTransactionResponse {
	this := HandlerTreasuryMiscTransactionResponse{}
	return &this
}

// NewHandlerTreasuryMiscTransactionResponseWithDefaults instantiates a new HandlerTreasuryMiscTransactionResponse object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewHandlerTreasuryMiscTransactionResponseWithDefaults() *HandlerTreasuryMiscTransactionResponse {
	this := HandlerTreasuryMiscTransactionResponse{}
	return &this
}

// GetAccountDescdetails returns the AccountDescdetails field value if set, zero value otherwise.
func (o *HandlerTreasuryMiscTransactionResponse) GetAccountDescdetails() []HandlerAccountDescdetails {
	if o == nil || IsNil(o.AccountDescdetails) {
		var ret []HandlerAccountDescdetails
		return ret
	}
	return o.AccountDescdetails
}

// GetAccountDescdetailsOk returns a tuple with the AccountDescdetails field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *HandlerTreasuryMiscTransactionResponse) GetAccountDescdetailsOk() ([]HandlerAccountDescdetails, bool) {
	if o == nil || IsNil(o.AccountDescdetails) {
		return nil, false
	}
	return o.AccountDescdetails, true
}

// HasAccountDescdetails returns a boolean if a field has been set.
func (o *HandlerTreasuryMiscTransactionResponse) HasAccountDescdetails() bool {
	if o != nil && !IsNil(o.AccountDescdetails) {
		return true
	}

	return false
}

// SetAccountDescdetails gets a reference to the given []HandlerAccountDescdetails and assigns it to the AccountDescdetails field.
func (o *HandlerTreasuryMiscTransactionResponse) SetAccountDescdetails(v []HandlerAccountDescdetails) {
	o.AccountDescdetails = v
}

// GetApproverDate returns the ApproverDate field value if set, zero value otherwise.
func (o *HandlerTreasuryMiscTransactionResponse) GetApproverDate() string {
	if o == nil || IsNil(o.ApproverDate) {
		var ret string
		return ret
	}
	return *o.ApproverDate
}

// GetApproverDateOk returns a tuple with the ApproverDate field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *HandlerTreasuryMiscTransactionResponse) GetApproverDateOk() (*string, bool) {
	if o == nil || IsNil(o.ApproverDate) {
		return nil, false
	}
	return o.ApproverDate, true
}

// HasApproverDate returns a boolean if a field has been set.
func (o *HandlerTreasuryMiscTransactionResponse) HasApproverDate() bool {
	if o != nil && !IsNil(o.ApproverDate) {
		return true
	}

	return false
}

// SetApproverDate gets a reference to the given string and assigns it to the ApproverDate field.
func (o *HandlerTreasuryMiscTransactionResponse) SetApproverDate(v string) {
	o.ApproverDate = &v
}

// GetApproverId returns the ApproverId field value if set, zero value otherwise.
func (o *HandlerTreasuryMiscTransactionResponse) GetApproverId() int32 {
	if o == nil || IsNil(o.ApproverId) {
		var ret int32
		return ret
	}
	return *o.ApproverId
}

// GetApproverIdOk returns a tuple with the ApproverId field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *HandlerTreasuryMiscTransactionResponse) GetApproverIdOk() (*int32, bool) {
	if o == nil || IsNil(o.ApproverId) {
		return nil, false
	}
	return o.ApproverId, true
}

// HasApproverId returns a boolean if a field has been set.
func (o *HandlerTreasuryMiscTransactionResponse) HasApproverId() bool {
	if o != nil && !IsNil(o.ApproverId) {
		return true
	}

	return false
}

// SetApproverId gets a reference to the given int32 and assigns it to the ApproverId field.
func (o *HandlerTreasuryMiscTransactionResponse) SetApproverId(v int32) {
	o.ApproverId = &v
}

// GetApproverRemarks returns the ApproverRemarks field value if set, zero value otherwise.
func (o *HandlerTreasuryMiscTransactionResponse) GetApproverRemarks() string {
	if o == nil || IsNil(o.ApproverRemarks) {
		var ret string
		return ret
	}
	return *o.ApproverRemarks
}

// GetApproverRemarksOk returns a tuple with the ApproverRemarks field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *HandlerTreasuryMiscTransactionResponse) GetApproverRemarksOk() (*string, bool) {
	if o == nil || IsNil(o.ApproverRemarks) {
		return nil, false
	}
	return o.ApproverRemarks, true
}

// HasApproverRemarks returns a boolean if a field has been set.
func (o *HandlerTreasuryMiscTransactionResponse) HasApproverRemarks() bool {
	if o != nil && !IsNil(o.ApproverRemarks) {
		return true
	}

	return false
}

// SetApproverRemarks gets a reference to the given string and assigns it to the ApproverRemarks field.
func (o *HandlerTreasuryMiscTransactionResponse) SetApproverRemarks(v string) {
	o.ApproverRemarks = &v
}

// GetIsApproved returns the IsApproved field value if set, zero value otherwise.
func (o *HandlerTreasuryMiscTransactionResponse) GetIsApproved() bool {
	if o == nil || IsNil(o.IsApproved) {
		var ret bool
		return ret
	}
	return *o.IsApproved
}

// GetIsApprovedOk returns a tuple with the IsApproved field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *HandlerTreasuryMiscTransactionResponse) GetIsApprovedOk() (*bool, bool) {
	if o == nil || IsNil(o.IsApproved) {
		return nil, false
	}
	return o.IsApproved, true
}

// HasIsApproved returns a boolean if a field has been set.
func (o *HandlerTreasuryMiscTransactionResponse) HasIsApproved() bool {
	if o != nil && !IsNil(o.IsApproved) {
		return true
	}

	return false
}

// SetIsApproved gets a reference to the given bool and assigns it to the IsApproved field.
func (o *HandlerTreasuryMiscTransactionResponse) SetIsApproved(v bool) {
	o.IsApproved = &v
}

// GetOfficeId returns the OfficeId field value if set, zero value otherwise.
func (o *HandlerTreasuryMiscTransactionResponse) GetOfficeId() int32 {
	if o == nil || IsNil(o.OfficeId) {
		var ret int32
		return ret
	}
	return *o.OfficeId
}

// GetOfficeIdOk returns a tuple with the OfficeId field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *HandlerTreasuryMiscTransactionResponse) GetOfficeIdOk() (*int32, bool) {
	if o == nil || IsNil(o.OfficeId) {
		return nil, false
	}
	return o.OfficeId, true
}

// HasOfficeId returns a boolean if a field has been set.
func (o *HandlerTreasuryMiscTransactionResponse) HasOfficeId() bool {
	if o != nil && !IsNil(o.OfficeId) {
		return true
	}

	return false
}

// SetOfficeId gets a reference to the given int32 and assigns it to the OfficeId field.
func (o *HandlerTreasuryMiscTransactionResponse) SetOfficeId(v int32) {
	o.OfficeId = &v
}

// GetRemarks returns the Remarks field value if set, zero value otherwise.
func (o *HandlerTreasuryMiscTransactionResponse) GetRemarks() string {
	if o == nil || IsNil(o.Remarks) {
		var ret string
		return ret
	}
	return *o.Remarks
}

// GetRemarksOk returns a tuple with the Remarks field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *HandlerTreasuryMiscTransactionResponse) GetRemarksOk() (*string, bool) {
	if o == nil || IsNil(o.Remarks) {
		return nil, false
	}
	return o.Remarks, true
}

// HasRemarks returns a boolean if a field has been set.
func (o *HandlerTreasuryMiscTransactionResponse) HasRemarks() bool {
	if o != nil && !IsNil(o.Remarks) {
		return true
	}

	return false
}

// SetRemarks gets a reference to the given string and assigns it to the Remarks field.
func (o *HandlerTreasuryMiscTransactionResponse) SetRemarks(v string) {
	o.Remarks = &v
}

// GetReqAmount returns the ReqAmount field value if set, zero value otherwise.
func (o *HandlerTreasuryMiscTransactionResponse) GetReqAmount() float32 {
	if o == nil || IsNil(o.ReqAmount) {
		var ret float32
		return ret
	}
	return *o.ReqAmount
}

// GetReqAmountOk returns a tuple with the ReqAmount field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *HandlerTreasuryMiscTransactionResponse) GetReqAmountOk() (*float32, bool) {
	if o == nil || IsNil(o.ReqAmount) {
		return nil, false
	}
	return o.ReqAmount, true
}

// HasReqAmount returns a boolean if a field has been set.
func (o *HandlerTreasuryMiscTransactionResponse) HasReqAmount() bool {
	if o != nil && !IsNil(o.ReqAmount) {
		return true
	}

	return false
}

// SetReqAmount gets a reference to the given float32 and assigns it to the ReqAmount field.
func (o *HandlerTreasuryMiscTransactionResponse) SetReqAmount(v float32) {
	o.ReqAmount = &v
}

// GetReqDetails returns the ReqDetails field value if set, zero value otherwise.
func (o *HandlerTreasuryMiscTransactionResponse) GetReqDetails() map[string]float32 {
	if o == nil || IsNil(o.ReqDetails) {
		var ret map[string]float32
		return ret
	}
	return *o.ReqDetails
}

// GetReqDetailsOk returns a tuple with the ReqDetails field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *HandlerTreasuryMiscTransactionResponse) GetReqDetailsOk() (*map[string]float32, bool) {
	if o == nil || IsNil(o.ReqDetails) {
		return nil, false
	}
	return o.ReqDetails, true
}

// HasReqDetails returns a boolean if a field has been set.
func (o *HandlerTreasuryMiscTransactionResponse) HasReqDetails() bool {
	if o != nil && !IsNil(o.ReqDetails) {
		return true
	}

	return false
}

// SetReqDetails gets a reference to the given map[string]float32 and assigns it to the ReqDetails field.
func (o *HandlerTreasuryMiscTransactionResponse) SetReqDetails(v map[string]float32) {
	o.ReqDetails = &v
}

// GetRequestType returns the RequestType field value if set, zero value otherwise.
func (o *HandlerTreasuryMiscTransactionResponse) GetRequestType() string {
	if o == nil || IsNil(o.RequestType) {
		var ret string
		return ret
	}
	return *o.RequestType
}

// GetRequestTypeOk returns a tuple with the RequestType field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *HandlerTreasuryMiscTransactionResponse) GetRequestTypeOk() (*string, bool) {
	if o == nil || IsNil(o.RequestType) {
		return nil, false
	}
	return o.RequestType, true
}

// HasRequestType returns a boolean if a field has been set.
func (o *HandlerTreasuryMiscTransactionResponse) HasRequestType() bool {
	if o != nil && !IsNil(o.RequestType) {
		return true
	}

	return false
}

// SetRequestType gets a reference to the given string and assigns it to the RequestType field.
func (o *HandlerTreasuryMiscTransactionResponse) SetRequestType(v string) {
	o.RequestType = &v
}

// GetTransDate returns the TransDate field value if set, zero value otherwise.
func (o *HandlerTreasuryMiscTransactionResponse) GetTransDate() string {
	if o == nil || IsNil(o.TransDate) {
		var ret string
		return ret
	}
	return *o.TransDate
}

// GetTransDateOk returns a tuple with the TransDate field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *HandlerTreasuryMiscTransactionResponse) GetTransDateOk() (*string, bool) {
	if o == nil || IsNil(o.TransDate) {
		return nil, false
	}
	return o.TransDate, true
}

// HasTransDate returns a boolean if a field has been set.
func (o *HandlerTreasuryMiscTransactionResponse) HasTransDate() bool {
	if o != nil && !IsNil(o.TransDate) {
		return true
	}

	return false
}

// SetTransDate gets a reference to the given string and assigns it to the TransDate field.
func (o *HandlerTreasuryMiscTransactionResponse) SetTransDate(v string) {
	o.TransDate = &v
}

// GetTransactionId returns the TransactionId field value if set, zero value otherwise.
func (o *HandlerTreasuryMiscTransactionResponse) GetTransactionId() string {
	if o == nil || IsNil(o.TransactionId) {
		var ret string
		return ret
	}
	return *o.TransactionId
}

// GetTransactionIdOk returns a tuple with the TransactionId field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *HandlerTreasuryMiscTransactionResponse) GetTransactionIdOk() (*string, bool) {
	if o == nil || IsNil(o.TransactionId) {
		return nil, false
	}
	return o.TransactionId, true
}

// HasTransactionId returns a boolean if a field has been set.
func (o *HandlerTreasuryMiscTransactionResponse) HasTransactionId() bool {
	if o != nil && !IsNil(o.TransactionId) {
		return true
	}

	return false
}

// SetTransactionId gets a reference to the given string and assigns it to the TransactionId field.
func (o *HandlerTreasuryMiscTransactionResponse) SetTransactionId(v string) {
	o.TransactionId = &v
}

// GetTxnMode returns the TxnMode field value if set, zero value otherwise.
func (o *HandlerTreasuryMiscTransactionResponse) GetTxnMode() string {
	if o == nil || IsNil(o.TxnMode) {
		var ret string
		return ret
	}
	return *o.TxnMode
}

// GetTxnModeOk returns a tuple with the TxnMode field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *HandlerTreasuryMiscTransactionResponse) GetTxnModeOk() (*string, bool) {
	if o == nil || IsNil(o.TxnMode) {
		return nil, false
	}
	return o.TxnMode, true
}

// HasTxnMode returns a boolean if a field has been set.
func (o *HandlerTreasuryMiscTransactionResponse) HasTxnMode() bool {
	if o != nil && !IsNil(o.TxnMode) {
		return true
	}

	return false
}

// SetTxnMode gets a reference to the given string and assigns it to the TxnMode field.
func (o *HandlerTreasuryMiscTransactionResponse) SetTxnMode(v string) {
	o.TxnMode = &v
}

// GetUserId returns the UserId field value if set, zero value otherwise.
func (o *HandlerTreasuryMiscTransactionResponse) GetUserId() int32 {
	if o == nil || IsNil(o.UserId) {
		var ret int32
		return ret
	}
	return *o.UserId
}

// GetUserIdOk returns a tuple with the UserId field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *HandlerTreasuryMiscTransactionResponse) GetUserIdOk() (*int32, bool) {
	if o == nil || IsNil(o.UserId) {
		return nil, false
	}
	return o.UserId, true
}

// HasUserId returns a boolean if a field has been set.
func (o *HandlerTreasuryMiscTransactionResponse) HasUserId() bool {
	if o != nil && !IsNil(o.UserId) {
		return true
	}

	return false
}

// SetUserId gets a reference to the given int32 and assigns it to the UserId field.
func (o *HandlerTreasuryMiscTransactionResponse) SetUserId(v int32) {
	o.UserId = &v
}

func (o HandlerTreasuryMiscTransactionResponse) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o HandlerTreasuryMiscTransactionResponse) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.AccountDescdetails) {
		toSerialize["accountDescdetails"] = o.AccountDescdetails
	}
	if !IsNil(o.ApproverDate) {
		toSerialize["approver_date"] = o.ApproverDate
	}
	if !IsNil(o.ApproverId) {
		toSerialize["approver_id"] = o.ApproverId
	}
	if !IsNil(o.ApproverRemarks) {
		toSerialize["approver_remarks"] = o.ApproverRemarks
	}
	if !IsNil(o.IsApproved) {
		toSerialize["is_approved"] = o.IsApproved
	}
	if !IsNil(o.OfficeId) {
		toSerialize["office_id"] = o.OfficeId
	}
	if !IsNil(o.Remarks) {
		toSerialize["remarks"] = o.Remarks
	}
	if !IsNil(o.ReqAmount) {
		toSerialize["req_amount"] = o.ReqAmount
	}
	if !IsNil(o.ReqDetails) {
		toSerialize["req_details"] = o.ReqDetails
	}
	if !IsNil(o.RequestType) {
		toSerialize["request_type"] = o.RequestType
	}
	if !IsNil(o.TransDate) {
		toSerialize["trans_date"] = o.TransDate
	}
	if !IsNil(o.TransactionId) {
		toSerialize["transaction_id"] = o.TransactionId
	}
	if !IsNil(o.TxnMode) {
		toSerialize["txn_mode"] = o.TxnMode
	}
	if !IsNil(o.UserId) {
		toSerialize["user_id"] = o.UserId
	}
	return toSerialize, nil
}

type NullableHandlerTreasuryMiscTransactionResponse struct {
	value *HandlerTreasuryMiscTransactionResponse
	isSet bool
}

func (v NullableHandlerTreasuryMiscTransactionResponse) Get() *HandlerTreasuryMiscTransactionResponse {
	return v.value
}

func (v *NullableHandlerTreasuryMiscTransactionResponse) Set(val *HandlerTreasuryMiscTransactionResponse) {
	v.value = val
	v.isSet = true
}

func (v NullableHandlerTreasuryMiscTransactionResponse) IsSet() bool {
	return v.isSet
}

func (v *NullableHandlerTreasuryMiscTransactionResponse) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableHandlerTreasuryMiscTransactionResponse(val *HandlerTreasuryMiscTransactionResponse) *NullableHandlerTreasuryMiscTransactionResponse {
	return &NullableHandlerTreasuryMiscTransactionResponse{value: val, isSet: true}
}

func (v NullableHandlerTreasuryMiscTransactionResponse) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableHandlerTreasuryMiscTransactionResponse) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


