/*
Treasury Management API

A comprehensive API for managing addresses, offering endpoints for creation, update, deletion, and retrieval of address data.

API version: 1.0
Contact: support_cept@indiapost.gov.in
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
)

// checks if the ResponseCreateDayBeginEnd type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &ResponseCreateDayBeginEnd{}

// ResponseCreateDayBeginEnd struct for ResponseCreateDayBeginEnd
type ResponseCreateDayBeginEnd struct {
	OfficeId *int32 `json:"office_id,omitempty"`
}

// NewResponseCreateDayBeginEnd instantiates a new ResponseCreateDayBeginEnd object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewResponseCreateDayBeginEnd() *ResponseCreateDayBeginEnd {
	this := ResponseCreateDayBeginEnd{}
	return &this
}

// NewResponseCreateDayBeginEndWithDefaults instantiates a new ResponseCreateDayBeginEnd object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewResponseCreateDayBeginEndWithDefaults() *ResponseCreateDayBeginEnd {
	this := ResponseCreateDayBeginEnd{}
	return &this
}

// GetOfficeId returns the OfficeId field value if set, zero value otherwise.
func (o *ResponseCreateDayBeginEnd) GetOfficeId() int32 {
	if o == nil || IsNil(o.OfficeId) {
		var ret int32
		return ret
	}
	return *o.OfficeId
}

// GetOfficeIdOk returns a tuple with the OfficeId field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ResponseCreateDayBeginEnd) GetOfficeIdOk() (*int32, bool) {
	if o == nil || IsNil(o.OfficeId) {
		return nil, false
	}
	return o.OfficeId, true
}

// HasOfficeId returns a boolean if a field has been set.
func (o *ResponseCreateDayBeginEnd) HasOfficeId() bool {
	if o != nil && !IsNil(o.OfficeId) {
		return true
	}

	return false
}

// SetOfficeId gets a reference to the given int32 and assigns it to the OfficeId field.
func (o *ResponseCreateDayBeginEnd) SetOfficeId(v int32) {
	o.OfficeId = &v
}

func (o ResponseCreateDayBeginEnd) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o ResponseCreateDayBeginEnd) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.OfficeId) {
		toSerialize["office_id"] = o.OfficeId
	}
	return toSerialize, nil
}

type NullableResponseCreateDayBeginEnd struct {
	value *ResponseCreateDayBeginEnd
	isSet bool
}

func (v NullableResponseCreateDayBeginEnd) Get() *ResponseCreateDayBeginEnd {
	return v.value
}

func (v *NullableResponseCreateDayBeginEnd) Set(val *ResponseCreateDayBeginEnd) {
	v.value = val
	v.isSet = true
}

func (v NullableResponseCreateDayBeginEnd) IsSet() bool {
	return v.isSet
}

func (v *NullableResponseCreateDayBeginEnd) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableResponseCreateDayBeginEnd(val *ResponseCreateDayBeginEnd) *NullableResponseCreateDayBeginEnd {
	return &NullableResponseCreateDayBeginEnd{value: val, isSet: true}
}

func (v NullableResponseCreateDayBeginEnd) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableResponseCreateDayBeginEnd) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


