/*
Treasury Management API

A comprehensive API for managing addresses, offering endpoints for creation, update, deletion, and retrieval of address data.

API version: 1.0
Contact: support_cept@indiapost.gov.in
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
)

// checks if the ResponseCreateStampsAdvanceTxnResponse type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &ResponseCreateStampsAdvanceTxnResponse{}

// ResponseCreateStampsAdvanceTxnResponse struct for ResponseCreateStampsAdvanceTxnResponse
type ResponseCreateStampsAdvanceTxnResponse struct {
	TranId *string `json:"tran_id,omitempty"`
}

// NewResponseCreateStampsAdvanceTxnResponse instantiates a new ResponseCreateStampsAdvanceTxnResponse object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewResponseCreateStampsAdvanceTxnResponse() *ResponseCreateStampsAdvanceTxnResponse {
	this := ResponseCreateStampsAdvanceTxnResponse{}
	return &this
}

// NewResponseCreateStampsAdvanceTxnResponseWithDefaults instantiates a new ResponseCreateStampsAdvanceTxnResponse object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewResponseCreateStampsAdvanceTxnResponseWithDefaults() *ResponseCreateStampsAdvanceTxnResponse {
	this := ResponseCreateStampsAdvanceTxnResponse{}
	return &this
}

// GetTranId returns the TranId field value if set, zero value otherwise.
func (o *ResponseCreateStampsAdvanceTxnResponse) GetTranId() string {
	if o == nil || IsNil(o.TranId) {
		var ret string
		return ret
	}
	return *o.TranId
}

// GetTranIdOk returns a tuple with the TranId field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ResponseCreateStampsAdvanceTxnResponse) GetTranIdOk() (*string, bool) {
	if o == nil || IsNil(o.TranId) {
		return nil, false
	}
	return o.TranId, true
}

// HasTranId returns a boolean if a field has been set.
func (o *ResponseCreateStampsAdvanceTxnResponse) HasTranId() bool {
	if o != nil && !IsNil(o.TranId) {
		return true
	}

	return false
}

// SetTranId gets a reference to the given string and assigns it to the TranId field.
func (o *ResponseCreateStampsAdvanceTxnResponse) SetTranId(v string) {
	o.TranId = &v
}

func (o ResponseCreateStampsAdvanceTxnResponse) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o ResponseCreateStampsAdvanceTxnResponse) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.TranId) {
		toSerialize["tran_id"] = o.TranId
	}
	return toSerialize, nil
}

type NullableResponseCreateStampsAdvanceTxnResponse struct {
	value *ResponseCreateStampsAdvanceTxnResponse
	isSet bool
}

func (v NullableResponseCreateStampsAdvanceTxnResponse) Get() *ResponseCreateStampsAdvanceTxnResponse {
	return v.value
}

func (v *NullableResponseCreateStampsAdvanceTxnResponse) Set(val *ResponseCreateStampsAdvanceTxnResponse) {
	v.value = val
	v.isSet = true
}

func (v NullableResponseCreateStampsAdvanceTxnResponse) IsSet() bool {
	return v.isSet
}

func (v *NullableResponseCreateStampsAdvanceTxnResponse) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableResponseCreateStampsAdvanceTxnResponse(val *ResponseCreateStampsAdvanceTxnResponse) *NullableResponseCreateStampsAdvanceTxnResponse {
	return &NullableResponseCreateStampsAdvanceTxnResponse{value: val, isSet: true}
}

func (v NullableResponseCreateStampsAdvanceTxnResponse) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableResponseCreateStampsAdvanceTxnResponse) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


