/*
Treasury Management API

A comprehensive API for managing addresses, offering endpoints for creation, update, deletion, and retrieval of address data.

API version: 1.0
Contact: support_cept@indiapost.gov.in
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
)

// checks if the ResponseCreateStampsDenominationsResponse type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &ResponseCreateStampsDenominationsResponse{}

// ResponseCreateStampsDenominationsResponse struct for ResponseCreateStampsDenominationsResponse
type ResponseCreateStampsDenominationsResponse struct {
	CategoryId *string `json:"category_id,omitempty"`
}

// NewResponseCreateStampsDenominationsResponse instantiates a new ResponseCreateStampsDenominationsResponse object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewResponseCreateStampsDenominationsResponse() *ResponseCreateStampsDenominationsResponse {
	this := ResponseCreateStampsDenominationsResponse{}
	return &this
}

// NewResponseCreateStampsDenominationsResponseWithDefaults instantiates a new ResponseCreateStampsDenominationsResponse object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewResponseCreateStampsDenominationsResponseWithDefaults() *ResponseCreateStampsDenominationsResponse {
	this := ResponseCreateStampsDenominationsResponse{}
	return &this
}

// GetCategoryId returns the CategoryId field value if set, zero value otherwise.
func (o *ResponseCreateStampsDenominationsResponse) GetCategoryId() string {
	if o == nil || IsNil(o.CategoryId) {
		var ret string
		return ret
	}
	return *o.CategoryId
}

// GetCategoryIdOk returns a tuple with the CategoryId field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ResponseCreateStampsDenominationsResponse) GetCategoryIdOk() (*string, bool) {
	if o == nil || IsNil(o.CategoryId) {
		return nil, false
	}
	return o.CategoryId, true
}

// HasCategoryId returns a boolean if a field has been set.
func (o *ResponseCreateStampsDenominationsResponse) HasCategoryId() bool {
	if o != nil && !IsNil(o.CategoryId) {
		return true
	}

	return false
}

// SetCategoryId gets a reference to the given string and assigns it to the CategoryId field.
func (o *ResponseCreateStampsDenominationsResponse) SetCategoryId(v string) {
	o.CategoryId = &v
}

func (o ResponseCreateStampsDenominationsResponse) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o ResponseCreateStampsDenominationsResponse) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.CategoryId) {
		toSerialize["category_id"] = o.CategoryId
	}
	return toSerialize, nil
}

type NullableResponseCreateStampsDenominationsResponse struct {
	value *ResponseCreateStampsDenominationsResponse
	isSet bool
}

func (v NullableResponseCreateStampsDenominationsResponse) Get() *ResponseCreateStampsDenominationsResponse {
	return v.value
}

func (v *NullableResponseCreateStampsDenominationsResponse) Set(val *ResponseCreateStampsDenominationsResponse) {
	v.value = val
	v.isSet = true
}

func (v NullableResponseCreateStampsDenominationsResponse) IsSet() bool {
	return v.isSet
}

func (v *NullableResponseCreateStampsDenominationsResponse) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableResponseCreateStampsDenominationsResponse(val *ResponseCreateStampsDenominationsResponse) *NullableResponseCreateStampsDenominationsResponse {
	return &NullableResponseCreateStampsDenominationsResponse{value: val, isSet: true}
}

func (v NullableResponseCreateStampsDenominationsResponse) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableResponseCreateStampsDenominationsResponse) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


