/*
Treasury Management API

A comprehensive API for managing addresses, offering endpoints for creation, update, deletion, and retrieval of address data.

API version: 1.0
Contact: support_cept@indiapost.gov.in
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
)

// checks if the ResponseCreateStampBulkSaleResponse type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &ResponseCreateStampBulkSaleResponse{}

// ResponseCreateStampBulkSaleResponse struct for ResponseCreateStampBulkSaleResponse
type ResponseCreateStampBulkSaleResponse struct {
	TranId *string `json:"tran_id,omitempty"`
}

// NewResponseCreateStampBulkSaleResponse instantiates a new ResponseCreateStampBulkSaleResponse object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewResponseCreateStampBulkSaleResponse() *ResponseCreateStampBulkSaleResponse {
	this := ResponseCreateStampBulkSaleResponse{}
	return &this
}

// NewResponseCreateStampBulkSaleResponseWithDefaults instantiates a new ResponseCreateStampBulkSaleResponse object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewResponseCreateStampBulkSaleResponseWithDefaults() *ResponseCreateStampBulkSaleResponse {
	this := ResponseCreateStampBulkSaleResponse{}
	return &this
}

// GetTranId returns the TranId field value if set, zero value otherwise.
func (o *ResponseCreateStampBulkSaleResponse) GetTranId() string {
	if o == nil || IsNil(o.TranId) {
		var ret string
		return ret
	}
	return *o.TranId
}

// GetTranIdOk returns a tuple with the TranId field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ResponseCreateStampBulkSaleResponse) GetTranIdOk() (*string, bool) {
	if o == nil || IsNil(o.TranId) {
		return nil, false
	}
	return o.TranId, true
}

// HasTranId returns a boolean if a field has been set.
func (o *ResponseCreateStampBulkSaleResponse) HasTranId() bool {
	if o != nil && !IsNil(o.TranId) {
		return true
	}

	return false
}

// SetTranId gets a reference to the given string and assigns it to the TranId field.
func (o *ResponseCreateStampBulkSaleResponse) SetTranId(v string) {
	o.TranId = &v
}

func (o ResponseCreateStampBulkSaleResponse) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o ResponseCreateStampBulkSaleResponse) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.TranId) {
		toSerialize["tran_id"] = o.TranId
	}
	return toSerialize, nil
}

type NullableResponseCreateStampBulkSaleResponse struct {
	value *ResponseCreateStampBulkSaleResponse
	isSet bool
}

func (v NullableResponseCreateStampBulkSaleResponse) Get() *ResponseCreateStampBulkSaleResponse {
	return v.value
}

func (v *NullableResponseCreateStampBulkSaleResponse) Set(val *ResponseCreateStampBulkSaleResponse) {
	v.value = val
	v.isSet = true
}

func (v NullableResponseCreateStampBulkSaleResponse) IsSet() bool {
	return v.isSet
}

func (v *NullableResponseCreateStampBulkSaleResponse) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableResponseCreateStampBulkSaleResponse(val *ResponseCreateStampBulkSaleResponse) *NullableResponseCreateStampBulkSaleResponse {
	return &NullableResponseCreateStampBulkSaleResponse{value: val, isSet: true}
}

func (v NullableResponseCreateStampBulkSaleResponse) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableResponseCreateStampBulkSaleResponse) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


