/*
Treasury Management API

A comprehensive API for managing addresses, offering endpoints for creation, update, deletion, and retrieval of address data.

API version: 1.0
Contact: support_cept@indiapost.gov.in
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the HandlerUpdateIPOsOBCSDReceiptsApproveRequest type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &HandlerUpdateIPOsOBCSDReceiptsApproveRequest{}

// HandlerUpdateIPOsOBCSDReceiptsApproveRequest struct for HandlerUpdateIPOsOBCSDReceiptsApproveRequest
type HandlerUpdateIPOsOBCSDReceiptsApproveRequest struct {
	ApprUserId int32 `json:"appr_user_id"`
	ApproverRemarks *string `json:"approver_remarks,omitempty"`
	IsApproved *bool `json:"is_approved,omitempty"`
}

type _HandlerUpdateIPOsOBCSDReceiptsApproveRequest HandlerUpdateIPOsOBCSDReceiptsApproveRequest

// NewHandlerUpdateIPOsOBCSDReceiptsApproveRequest instantiates a new HandlerUpdateIPOsOBCSDReceiptsApproveRequest object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewHandlerUpdateIPOsOBCSDReceiptsApproveRequest(apprUserId int32) *HandlerUpdateIPOsOBCSDReceiptsApproveRequest {
	this := HandlerUpdateIPOsOBCSDReceiptsApproveRequest{}
	this.ApprUserId = apprUserId
	return &this
}

// NewHandlerUpdateIPOsOBCSDReceiptsApproveRequestWithDefaults instantiates a new HandlerUpdateIPOsOBCSDReceiptsApproveRequest object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewHandlerUpdateIPOsOBCSDReceiptsApproveRequestWithDefaults() *HandlerUpdateIPOsOBCSDReceiptsApproveRequest {
	this := HandlerUpdateIPOsOBCSDReceiptsApproveRequest{}
	return &this
}

// GetApprUserId returns the ApprUserId field value
func (o *HandlerUpdateIPOsOBCSDReceiptsApproveRequest) GetApprUserId() int32 {
	if o == nil {
		var ret int32
		return ret
	}

	return o.ApprUserId
}

// GetApprUserIdOk returns a tuple with the ApprUserId field value
// and a boolean to check if the value has been set.
func (o *HandlerUpdateIPOsOBCSDReceiptsApproveRequest) GetApprUserIdOk() (*int32, bool) {
	if o == nil {
		return nil, false
	}
	return &o.ApprUserId, true
}

// SetApprUserId sets field value
func (o *HandlerUpdateIPOsOBCSDReceiptsApproveRequest) SetApprUserId(v int32) {
	o.ApprUserId = v
}

// GetApproverRemarks returns the ApproverRemarks field value if set, zero value otherwise.
func (o *HandlerUpdateIPOsOBCSDReceiptsApproveRequest) GetApproverRemarks() string {
	if o == nil || IsNil(o.ApproverRemarks) {
		var ret string
		return ret
	}
	return *o.ApproverRemarks
}

// GetApproverRemarksOk returns a tuple with the ApproverRemarks field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *HandlerUpdateIPOsOBCSDReceiptsApproveRequest) GetApproverRemarksOk() (*string, bool) {
	if o == nil || IsNil(o.ApproverRemarks) {
		return nil, false
	}
	return o.ApproverRemarks, true
}

// HasApproverRemarks returns a boolean if a field has been set.
func (o *HandlerUpdateIPOsOBCSDReceiptsApproveRequest) HasApproverRemarks() bool {
	if o != nil && !IsNil(o.ApproverRemarks) {
		return true
	}

	return false
}

// SetApproverRemarks gets a reference to the given string and assigns it to the ApproverRemarks field.
func (o *HandlerUpdateIPOsOBCSDReceiptsApproveRequest) SetApproverRemarks(v string) {
	o.ApproverRemarks = &v
}

// GetIsApproved returns the IsApproved field value if set, zero value otherwise.
func (o *HandlerUpdateIPOsOBCSDReceiptsApproveRequest) GetIsApproved() bool {
	if o == nil || IsNil(o.IsApproved) {
		var ret bool
		return ret
	}
	return *o.IsApproved
}

// GetIsApprovedOk returns a tuple with the IsApproved field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *HandlerUpdateIPOsOBCSDReceiptsApproveRequest) GetIsApprovedOk() (*bool, bool) {
	if o == nil || IsNil(o.IsApproved) {
		return nil, false
	}
	return o.IsApproved, true
}

// HasIsApproved returns a boolean if a field has been set.
func (o *HandlerUpdateIPOsOBCSDReceiptsApproveRequest) HasIsApproved() bool {
	if o != nil && !IsNil(o.IsApproved) {
		return true
	}

	return false
}

// SetIsApproved gets a reference to the given bool and assigns it to the IsApproved field.
func (o *HandlerUpdateIPOsOBCSDReceiptsApproveRequest) SetIsApproved(v bool) {
	o.IsApproved = &v
}

func (o HandlerUpdateIPOsOBCSDReceiptsApproveRequest) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o HandlerUpdateIPOsOBCSDReceiptsApproveRequest) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["appr_user_id"] = o.ApprUserId
	if !IsNil(o.ApproverRemarks) {
		toSerialize["approver_remarks"] = o.ApproverRemarks
	}
	if !IsNil(o.IsApproved) {
		toSerialize["is_approved"] = o.IsApproved
	}
	return toSerialize, nil
}

func (o *HandlerUpdateIPOsOBCSDReceiptsApproveRequest) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"appr_user_id",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varHandlerUpdateIPOsOBCSDReceiptsApproveRequest := _HandlerUpdateIPOsOBCSDReceiptsApproveRequest{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varHandlerUpdateIPOsOBCSDReceiptsApproveRequest)

	if err != nil {
		return err
	}

	*o = HandlerUpdateIPOsOBCSDReceiptsApproveRequest(varHandlerUpdateIPOsOBCSDReceiptsApproveRequest)

	return err
}

type NullableHandlerUpdateIPOsOBCSDReceiptsApproveRequest struct {
	value *HandlerUpdateIPOsOBCSDReceiptsApproveRequest
	isSet bool
}

func (v NullableHandlerUpdateIPOsOBCSDReceiptsApproveRequest) Get() *HandlerUpdateIPOsOBCSDReceiptsApproveRequest {
	return v.value
}

func (v *NullableHandlerUpdateIPOsOBCSDReceiptsApproveRequest) Set(val *HandlerUpdateIPOsOBCSDReceiptsApproveRequest) {
	v.value = val
	v.isSet = true
}

func (v NullableHandlerUpdateIPOsOBCSDReceiptsApproveRequest) IsSet() bool {
	return v.isSet
}

func (v *NullableHandlerUpdateIPOsOBCSDReceiptsApproveRequest) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableHandlerUpdateIPOsOBCSDReceiptsApproveRequest(val *HandlerUpdateIPOsOBCSDReceiptsApproveRequest) *NullableHandlerUpdateIPOsOBCSDReceiptsApproveRequest {
	return &NullableHandlerUpdateIPOsOBCSDReceiptsApproveRequest{value: val, isSet: true}
}

func (v NullableHandlerUpdateIPOsOBCSDReceiptsApproveRequest) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableHandlerUpdateIPOsOBCSDReceiptsApproveRequest) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


