/*
Treasury Management API

A comprehensive API for managing addresses, offering endpoints for creation, update, deletion, and retrieval of address data.

API version: 1.0
Contact: support_cept@indiapost.gov.in
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
)

// checks if the ResponseCreateOfficesResponse type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &ResponseCreateOfficesResponse{}

// ResponseCreateOfficesResponse struct for ResponseCreateOfficesResponse
type ResponseCreateOfficesResponse struct {
	TranId *string `json:"tran_id,omitempty"`
}

// NewResponseCreateOfficesResponse instantiates a new ResponseCreateOfficesResponse object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewResponseCreateOfficesResponse() *ResponseCreateOfficesResponse {
	this := ResponseCreateOfficesResponse{}
	return &this
}

// NewResponseCreateOfficesResponseWithDefaults instantiates a new ResponseCreateOfficesResponse object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewResponseCreateOfficesResponseWithDefaults() *ResponseCreateOfficesResponse {
	this := ResponseCreateOfficesResponse{}
	return &this
}

// GetTranId returns the TranId field value if set, zero value otherwise.
func (o *ResponseCreateOfficesResponse) GetTranId() string {
	if o == nil || IsNil(o.TranId) {
		var ret string
		return ret
	}
	return *o.TranId
}

// GetTranIdOk returns a tuple with the TranId field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ResponseCreateOfficesResponse) GetTranIdOk() (*string, bool) {
	if o == nil || IsNil(o.TranId) {
		return nil, false
	}
	return o.TranId, true
}

// HasTranId returns a boolean if a field has been set.
func (o *ResponseCreateOfficesResponse) HasTranId() bool {
	if o != nil && !IsNil(o.TranId) {
		return true
	}

	return false
}

// SetTranId gets a reference to the given string and assigns it to the TranId field.
func (o *ResponseCreateOfficesResponse) SetTranId(v string) {
	o.TranId = &v
}

func (o ResponseCreateOfficesResponse) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o ResponseCreateOfficesResponse) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.TranId) {
		toSerialize["tran_id"] = o.TranId
	}
	return toSerialize, nil
}

type NullableResponseCreateOfficesResponse struct {
	value *ResponseCreateOfficesResponse
	isSet bool
}

func (v NullableResponseCreateOfficesResponse) Get() *ResponseCreateOfficesResponse {
	return v.value
}

func (v *NullableResponseCreateOfficesResponse) Set(val *ResponseCreateOfficesResponse) {
	v.value = val
	v.isSet = true
}

func (v NullableResponseCreateOfficesResponse) IsSet() bool {
	return v.isSet
}

func (v *NullableResponseCreateOfficesResponse) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableResponseCreateOfficesResponse(val *ResponseCreateOfficesResponse) *NullableResponseCreateOfficesResponse {
	return &NullableResponseCreateOfficesResponse{value: val, isSet: true}
}

func (v NullableResponseCreateOfficesResponse) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableResponseCreateOfficesResponse) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


