/*
Treasury Management API

A comprehensive API for managing addresses, offering endpoints for creation, update, deletion, and retrieval of address data.

API version: 1.0
Contact: support_cept@indiapost.gov.in
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the HandlerCreateStampsAdvanceTxnsRequest type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &HandlerCreateStampsAdvanceTxnsRequest{}

// HandlerCreateStampsAdvanceTxnsRequest struct for HandlerCreateStampsAdvanceTxnsRequest
type HandlerCreateStampsAdvanceTxnsRequest struct {
	AdvAmt float32 `json:"adv_amt"`
	AdvTxnDetails map[string]int32 `json:"adv_txn_details"`
	AdvUserId int32 `json:"adv_user_id"`
	Remarks *string `json:"remarks,omitempty"`
	TransType string `json:"trans_type"`
	TryUserId int32 `json:"try_user_id"`
}

type _HandlerCreateStampsAdvanceTxnsRequest HandlerCreateStampsAdvanceTxnsRequest

// NewHandlerCreateStampsAdvanceTxnsRequest instantiates a new HandlerCreateStampsAdvanceTxnsRequest object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewHandlerCreateStampsAdvanceTxnsRequest(advAmt float32, advTxnDetails map[string]int32, advUserId int32, transType string, tryUserId int32) *HandlerCreateStampsAdvanceTxnsRequest {
	this := HandlerCreateStampsAdvanceTxnsRequest{}
	this.AdvAmt = advAmt
	this.AdvTxnDetails = advTxnDetails
	this.AdvUserId = advUserId
	this.TransType = transType
	this.TryUserId = tryUserId
	return &this
}

// NewHandlerCreateStampsAdvanceTxnsRequestWithDefaults instantiates a new HandlerCreateStampsAdvanceTxnsRequest object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewHandlerCreateStampsAdvanceTxnsRequestWithDefaults() *HandlerCreateStampsAdvanceTxnsRequest {
	this := HandlerCreateStampsAdvanceTxnsRequest{}
	return &this
}

// GetAdvAmt returns the AdvAmt field value
func (o *HandlerCreateStampsAdvanceTxnsRequest) GetAdvAmt() float32 {
	if o == nil {
		var ret float32
		return ret
	}

	return o.AdvAmt
}

// GetAdvAmtOk returns a tuple with the AdvAmt field value
// and a boolean to check if the value has been set.
func (o *HandlerCreateStampsAdvanceTxnsRequest) GetAdvAmtOk() (*float32, bool) {
	if o == nil {
		return nil, false
	}
	return &o.AdvAmt, true
}

// SetAdvAmt sets field value
func (o *HandlerCreateStampsAdvanceTxnsRequest) SetAdvAmt(v float32) {
	o.AdvAmt = v
}

// GetAdvTxnDetails returns the AdvTxnDetails field value
func (o *HandlerCreateStampsAdvanceTxnsRequest) GetAdvTxnDetails() map[string]int32 {
	if o == nil {
		var ret map[string]int32
		return ret
	}

	return o.AdvTxnDetails
}

// GetAdvTxnDetailsOk returns a tuple with the AdvTxnDetails field value
// and a boolean to check if the value has been set.
func (o *HandlerCreateStampsAdvanceTxnsRequest) GetAdvTxnDetailsOk() (*map[string]int32, bool) {
	if o == nil {
		return nil, false
	}
	return &o.AdvTxnDetails, true
}

// SetAdvTxnDetails sets field value
func (o *HandlerCreateStampsAdvanceTxnsRequest) SetAdvTxnDetails(v map[string]int32) {
	o.AdvTxnDetails = v
}

// GetAdvUserId returns the AdvUserId field value
func (o *HandlerCreateStampsAdvanceTxnsRequest) GetAdvUserId() int32 {
	if o == nil {
		var ret int32
		return ret
	}

	return o.AdvUserId
}

// GetAdvUserIdOk returns a tuple with the AdvUserId field value
// and a boolean to check if the value has been set.
func (o *HandlerCreateStampsAdvanceTxnsRequest) GetAdvUserIdOk() (*int32, bool) {
	if o == nil {
		return nil, false
	}
	return &o.AdvUserId, true
}

// SetAdvUserId sets field value
func (o *HandlerCreateStampsAdvanceTxnsRequest) SetAdvUserId(v int32) {
	o.AdvUserId = v
}

// GetRemarks returns the Remarks field value if set, zero value otherwise.
func (o *HandlerCreateStampsAdvanceTxnsRequest) GetRemarks() string {
	if o == nil || IsNil(o.Remarks) {
		var ret string
		return ret
	}
	return *o.Remarks
}

// GetRemarksOk returns a tuple with the Remarks field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *HandlerCreateStampsAdvanceTxnsRequest) GetRemarksOk() (*string, bool) {
	if o == nil || IsNil(o.Remarks) {
		return nil, false
	}
	return o.Remarks, true
}

// HasRemarks returns a boolean if a field has been set.
func (o *HandlerCreateStampsAdvanceTxnsRequest) HasRemarks() bool {
	if o != nil && !IsNil(o.Remarks) {
		return true
	}

	return false
}

// SetRemarks gets a reference to the given string and assigns it to the Remarks field.
func (o *HandlerCreateStampsAdvanceTxnsRequest) SetRemarks(v string) {
	o.Remarks = &v
}

// GetTransType returns the TransType field value
func (o *HandlerCreateStampsAdvanceTxnsRequest) GetTransType() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.TransType
}

// GetTransTypeOk returns a tuple with the TransType field value
// and a boolean to check if the value has been set.
func (o *HandlerCreateStampsAdvanceTxnsRequest) GetTransTypeOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.TransType, true
}

// SetTransType sets field value
func (o *HandlerCreateStampsAdvanceTxnsRequest) SetTransType(v string) {
	o.TransType = v
}

// GetTryUserId returns the TryUserId field value
func (o *HandlerCreateStampsAdvanceTxnsRequest) GetTryUserId() int32 {
	if o == nil {
		var ret int32
		return ret
	}

	return o.TryUserId
}

// GetTryUserIdOk returns a tuple with the TryUserId field value
// and a boolean to check if the value has been set.
func (o *HandlerCreateStampsAdvanceTxnsRequest) GetTryUserIdOk() (*int32, bool) {
	if o == nil {
		return nil, false
	}
	return &o.TryUserId, true
}

// SetTryUserId sets field value
func (o *HandlerCreateStampsAdvanceTxnsRequest) SetTryUserId(v int32) {
	o.TryUserId = v
}

func (o HandlerCreateStampsAdvanceTxnsRequest) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o HandlerCreateStampsAdvanceTxnsRequest) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["adv_amt"] = o.AdvAmt
	toSerialize["adv_txn_details"] = o.AdvTxnDetails
	toSerialize["adv_user_id"] = o.AdvUserId
	if !IsNil(o.Remarks) {
		toSerialize["remarks"] = o.Remarks
	}
	toSerialize["trans_type"] = o.TransType
	toSerialize["try_user_id"] = o.TryUserId
	return toSerialize, nil
}

func (o *HandlerCreateStampsAdvanceTxnsRequest) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"adv_amt",
		"adv_txn_details",
		"adv_user_id",
		"trans_type",
		"try_user_id",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varHandlerCreateStampsAdvanceTxnsRequest := _HandlerCreateStampsAdvanceTxnsRequest{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varHandlerCreateStampsAdvanceTxnsRequest)

	if err != nil {
		return err
	}

	*o = HandlerCreateStampsAdvanceTxnsRequest(varHandlerCreateStampsAdvanceTxnsRequest)

	return err
}

type NullableHandlerCreateStampsAdvanceTxnsRequest struct {
	value *HandlerCreateStampsAdvanceTxnsRequest
	isSet bool
}

func (v NullableHandlerCreateStampsAdvanceTxnsRequest) Get() *HandlerCreateStampsAdvanceTxnsRequest {
	return v.value
}

func (v *NullableHandlerCreateStampsAdvanceTxnsRequest) Set(val *HandlerCreateStampsAdvanceTxnsRequest) {
	v.value = val
	v.isSet = true
}

func (v NullableHandlerCreateStampsAdvanceTxnsRequest) IsSet() bool {
	return v.isSet
}

func (v *NullableHandlerCreateStampsAdvanceTxnsRequest) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableHandlerCreateStampsAdvanceTxnsRequest(val *HandlerCreateStampsAdvanceTxnsRequest) *NullableHandlerCreateStampsAdvanceTxnsRequest {
	return &NullableHandlerCreateStampsAdvanceTxnsRequest{value: val, isSet: true}
}

func (v NullableHandlerCreateStampsAdvanceTxnsRequest) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableHandlerCreateStampsAdvanceTxnsRequest) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


