/*
Treasury Management API

A comprehensive API for managing addresses, offering endpoints for creation, update, deletion, and retrieval of address data.

API version: 1.0
Contact: support_cept@indiapost.gov.in
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
)

// checks if the ResponseCashBalanceAPIResponse type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &ResponseCashBalanceAPIResponse{}

// ResponseCashBalanceAPIResponse struct for ResponseCashBalanceAPIResponse
type ResponseCashBalanceAPIResponse struct {
	Data []ResponseCashBalance `json:"data,omitempty"`
	Message *string `json:"message,omitempty"`
	StatusCode *int32 `json:"status_code,omitempty"`
}

// NewResponseCashBalanceAPIResponse instantiates a new ResponseCashBalanceAPIResponse object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewResponseCashBalanceAPIResponse() *ResponseCashBalanceAPIResponse {
	this := ResponseCashBalanceAPIResponse{}
	return &this
}

// NewResponseCashBalanceAPIResponseWithDefaults instantiates a new ResponseCashBalanceAPIResponse object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewResponseCashBalanceAPIResponseWithDefaults() *ResponseCashBalanceAPIResponse {
	this := ResponseCashBalanceAPIResponse{}
	return &this
}

// GetData returns the Data field value if set, zero value otherwise.
func (o *ResponseCashBalanceAPIResponse) GetData() []ResponseCashBalance {
	if o == nil || IsNil(o.Data) {
		var ret []ResponseCashBalance
		return ret
	}
	return o.Data
}

// GetDataOk returns a tuple with the Data field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ResponseCashBalanceAPIResponse) GetDataOk() ([]ResponseCashBalance, bool) {
	if o == nil || IsNil(o.Data) {
		return nil, false
	}
	return o.Data, true
}

// HasData returns a boolean if a field has been set.
func (o *ResponseCashBalanceAPIResponse) HasData() bool {
	if o != nil && !IsNil(o.Data) {
		return true
	}

	return false
}

// SetData gets a reference to the given []ResponseCashBalance and assigns it to the Data field.
func (o *ResponseCashBalanceAPIResponse) SetData(v []ResponseCashBalance) {
	o.Data = v
}

// GetMessage returns the Message field value if set, zero value otherwise.
func (o *ResponseCashBalanceAPIResponse) GetMessage() string {
	if o == nil || IsNil(o.Message) {
		var ret string
		return ret
	}
	return *o.Message
}

// GetMessageOk returns a tuple with the Message field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ResponseCashBalanceAPIResponse) GetMessageOk() (*string, bool) {
	if o == nil || IsNil(o.Message) {
		return nil, false
	}
	return o.Message, true
}

// HasMessage returns a boolean if a field has been set.
func (o *ResponseCashBalanceAPIResponse) HasMessage() bool {
	if o != nil && !IsNil(o.Message) {
		return true
	}

	return false
}

// SetMessage gets a reference to the given string and assigns it to the Message field.
func (o *ResponseCashBalanceAPIResponse) SetMessage(v string) {
	o.Message = &v
}

// GetStatusCode returns the StatusCode field value if set, zero value otherwise.
func (o *ResponseCashBalanceAPIResponse) GetStatusCode() int32 {
	if o == nil || IsNil(o.StatusCode) {
		var ret int32
		return ret
	}
	return *o.StatusCode
}

// GetStatusCodeOk returns a tuple with the StatusCode field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ResponseCashBalanceAPIResponse) GetStatusCodeOk() (*int32, bool) {
	if o == nil || IsNil(o.StatusCode) {
		return nil, false
	}
	return o.StatusCode, true
}

// HasStatusCode returns a boolean if a field has been set.
func (o *ResponseCashBalanceAPIResponse) HasStatusCode() bool {
	if o != nil && !IsNil(o.StatusCode) {
		return true
	}

	return false
}

// SetStatusCode gets a reference to the given int32 and assigns it to the StatusCode field.
func (o *ResponseCashBalanceAPIResponse) SetStatusCode(v int32) {
	o.StatusCode = &v
}

func (o ResponseCashBalanceAPIResponse) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o ResponseCashBalanceAPIResponse) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Data) {
		toSerialize["data"] = o.Data
	}
	if !IsNil(o.Message) {
		toSerialize["message"] = o.Message
	}
	if !IsNil(o.StatusCode) {
		toSerialize["status_code"] = o.StatusCode
	}
	return toSerialize, nil
}

type NullableResponseCashBalanceAPIResponse struct {
	value *ResponseCashBalanceAPIResponse
	isSet bool
}

func (v NullableResponseCashBalanceAPIResponse) Get() *ResponseCashBalanceAPIResponse {
	return v.value
}

func (v *NullableResponseCashBalanceAPIResponse) Set(val *ResponseCashBalanceAPIResponse) {
	v.value = val
	v.isSet = true
}

func (v NullableResponseCashBalanceAPIResponse) IsSet() bool {
	return v.isSet
}

func (v *NullableResponseCashBalanceAPIResponse) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableResponseCashBalanceAPIResponse(val *ResponseCashBalanceAPIResponse) *NullableResponseCashBalanceAPIResponse {
	return &NullableResponseCashBalanceAPIResponse{value: val, isSet: true}
}

func (v NullableResponseCashBalanceAPIResponse) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableResponseCashBalanceAPIResponse) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


