/*
Treasury Management API

A comprehensive API for managing addresses, offering endpoints for creation, update, deletion, and retrieval of address data.

API version: 1.0
Contact: support_cept@indiapost.gov.in
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
)

// checks if the ResponseUpdateStampsInventoryAPIResponse type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &ResponseUpdateStampsInventoryAPIResponse{}

// ResponseUpdateStampsInventoryAPIResponse struct for ResponseUpdateStampsInventoryAPIResponse
type ResponseUpdateStampsInventoryAPIResponse struct {
	Message *string `json:"message,omitempty"`
	StatusCode *int32 `json:"status_code,omitempty"`
}

// NewResponseUpdateStampsInventoryAPIResponse instantiates a new ResponseUpdateStampsInventoryAPIResponse object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewResponseUpdateStampsInventoryAPIResponse() *ResponseUpdateStampsInventoryAPIResponse {
	this := ResponseUpdateStampsInventoryAPIResponse{}
	return &this
}

// NewResponseUpdateStampsInventoryAPIResponseWithDefaults instantiates a new ResponseUpdateStampsInventoryAPIResponse object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewResponseUpdateStampsInventoryAPIResponseWithDefaults() *ResponseUpdateStampsInventoryAPIResponse {
	this := ResponseUpdateStampsInventoryAPIResponse{}
	return &this
}

// GetMessage returns the Message field value if set, zero value otherwise.
func (o *ResponseUpdateStampsInventoryAPIResponse) GetMessage() string {
	if o == nil || IsNil(o.Message) {
		var ret string
		return ret
	}
	return *o.Message
}

// GetMessageOk returns a tuple with the Message field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ResponseUpdateStampsInventoryAPIResponse) GetMessageOk() (*string, bool) {
	if o == nil || IsNil(o.Message) {
		return nil, false
	}
	return o.Message, true
}

// HasMessage returns a boolean if a field has been set.
func (o *ResponseUpdateStampsInventoryAPIResponse) HasMessage() bool {
	if o != nil && !IsNil(o.Message) {
		return true
	}

	return false
}

// SetMessage gets a reference to the given string and assigns it to the Message field.
func (o *ResponseUpdateStampsInventoryAPIResponse) SetMessage(v string) {
	o.Message = &v
}

// GetStatusCode returns the StatusCode field value if set, zero value otherwise.
func (o *ResponseUpdateStampsInventoryAPIResponse) GetStatusCode() int32 {
	if o == nil || IsNil(o.StatusCode) {
		var ret int32
		return ret
	}
	return *o.StatusCode
}

// GetStatusCodeOk returns a tuple with the StatusCode field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ResponseUpdateStampsInventoryAPIResponse) GetStatusCodeOk() (*int32, bool) {
	if o == nil || IsNil(o.StatusCode) {
		return nil, false
	}
	return o.StatusCode, true
}

// HasStatusCode returns a boolean if a field has been set.
func (o *ResponseUpdateStampsInventoryAPIResponse) HasStatusCode() bool {
	if o != nil && !IsNil(o.StatusCode) {
		return true
	}

	return false
}

// SetStatusCode gets a reference to the given int32 and assigns it to the StatusCode field.
func (o *ResponseUpdateStampsInventoryAPIResponse) SetStatusCode(v int32) {
	o.StatusCode = &v
}

func (o ResponseUpdateStampsInventoryAPIResponse) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o ResponseUpdateStampsInventoryAPIResponse) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Message) {
		toSerialize["message"] = o.Message
	}
	if !IsNil(o.StatusCode) {
		toSerialize["status_code"] = o.StatusCode
	}
	return toSerialize, nil
}

type NullableResponseUpdateStampsInventoryAPIResponse struct {
	value *ResponseUpdateStampsInventoryAPIResponse
	isSet bool
}

func (v NullableResponseUpdateStampsInventoryAPIResponse) Get() *ResponseUpdateStampsInventoryAPIResponse {
	return v.value
}

func (v *NullableResponseUpdateStampsInventoryAPIResponse) Set(val *ResponseUpdateStampsInventoryAPIResponse) {
	v.value = val
	v.isSet = true
}

func (v NullableResponseUpdateStampsInventoryAPIResponse) IsSet() bool {
	return v.isSet
}

func (v *NullableResponseUpdateStampsInventoryAPIResponse) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableResponseUpdateStampsInventoryAPIResponse(val *ResponseUpdateStampsInventoryAPIResponse) *NullableResponseUpdateStampsInventoryAPIResponse {
	return &NullableResponseUpdateStampsInventoryAPIResponse{value: val, isSet: true}
}

func (v NullableResponseUpdateStampsInventoryAPIResponse) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableResponseUpdateStampsInventoryAPIResponse) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


