/*
Treasury Management API

A comprehensive API for managing addresses, offering endpoints for creation, update, deletion, and retrieval of address data.

API version: 1.0
Contact: support_cept@indiapost.gov.in
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
)

// checks if the ResponseExceptionalWkgDayResponse type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &ResponseExceptionalWkgDayResponse{}

// ResponseExceptionalWkgDayResponse struct for ResponseExceptionalWkgDayResponse
type ResponseExceptionalWkgDayResponse struct {
	ApproverDate *string `json:"approver_date,omitempty"`
	ApproverId *int32 `json:"approver_id,omitempty"`
	ExceptionalWkgDayDate *string `json:"exceptional_wkg_day_date,omitempty"`
	OfficeId *int32 `json:"office_id,omitempty"`
	OfficeName *string `json:"office_name,omitempty"`
	Remarks *string `json:"remarks,omitempty"`
}

// NewResponseExceptionalWkgDayResponse instantiates a new ResponseExceptionalWkgDayResponse object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewResponseExceptionalWkgDayResponse() *ResponseExceptionalWkgDayResponse {
	this := ResponseExceptionalWkgDayResponse{}
	return &this
}

// NewResponseExceptionalWkgDayResponseWithDefaults instantiates a new ResponseExceptionalWkgDayResponse object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewResponseExceptionalWkgDayResponseWithDefaults() *ResponseExceptionalWkgDayResponse {
	this := ResponseExceptionalWkgDayResponse{}
	return &this
}

// GetApproverDate returns the ApproverDate field value if set, zero value otherwise.
func (o *ResponseExceptionalWkgDayResponse) GetApproverDate() string {
	if o == nil || IsNil(o.ApproverDate) {
		var ret string
		return ret
	}
	return *o.ApproverDate
}

// GetApproverDateOk returns a tuple with the ApproverDate field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ResponseExceptionalWkgDayResponse) GetApproverDateOk() (*string, bool) {
	if o == nil || IsNil(o.ApproverDate) {
		return nil, false
	}
	return o.ApproverDate, true
}

// HasApproverDate returns a boolean if a field has been set.
func (o *ResponseExceptionalWkgDayResponse) HasApproverDate() bool {
	if o != nil && !IsNil(o.ApproverDate) {
		return true
	}

	return false
}

// SetApproverDate gets a reference to the given string and assigns it to the ApproverDate field.
func (o *ResponseExceptionalWkgDayResponse) SetApproverDate(v string) {
	o.ApproverDate = &v
}

// GetApproverId returns the ApproverId field value if set, zero value otherwise.
func (o *ResponseExceptionalWkgDayResponse) GetApproverId() int32 {
	if o == nil || IsNil(o.ApproverId) {
		var ret int32
		return ret
	}
	return *o.ApproverId
}

// GetApproverIdOk returns a tuple with the ApproverId field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ResponseExceptionalWkgDayResponse) GetApproverIdOk() (*int32, bool) {
	if o == nil || IsNil(o.ApproverId) {
		return nil, false
	}
	return o.ApproverId, true
}

// HasApproverId returns a boolean if a field has been set.
func (o *ResponseExceptionalWkgDayResponse) HasApproverId() bool {
	if o != nil && !IsNil(o.ApproverId) {
		return true
	}

	return false
}

// SetApproverId gets a reference to the given int32 and assigns it to the ApproverId field.
func (o *ResponseExceptionalWkgDayResponse) SetApproverId(v int32) {
	o.ApproverId = &v
}

// GetExceptionalWkgDayDate returns the ExceptionalWkgDayDate field value if set, zero value otherwise.
func (o *ResponseExceptionalWkgDayResponse) GetExceptionalWkgDayDate() string {
	if o == nil || IsNil(o.ExceptionalWkgDayDate) {
		var ret string
		return ret
	}
	return *o.ExceptionalWkgDayDate
}

// GetExceptionalWkgDayDateOk returns a tuple with the ExceptionalWkgDayDate field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ResponseExceptionalWkgDayResponse) GetExceptionalWkgDayDateOk() (*string, bool) {
	if o == nil || IsNil(o.ExceptionalWkgDayDate) {
		return nil, false
	}
	return o.ExceptionalWkgDayDate, true
}

// HasExceptionalWkgDayDate returns a boolean if a field has been set.
func (o *ResponseExceptionalWkgDayResponse) HasExceptionalWkgDayDate() bool {
	if o != nil && !IsNil(o.ExceptionalWkgDayDate) {
		return true
	}

	return false
}

// SetExceptionalWkgDayDate gets a reference to the given string and assigns it to the ExceptionalWkgDayDate field.
func (o *ResponseExceptionalWkgDayResponse) SetExceptionalWkgDayDate(v string) {
	o.ExceptionalWkgDayDate = &v
}

// GetOfficeId returns the OfficeId field value if set, zero value otherwise.
func (o *ResponseExceptionalWkgDayResponse) GetOfficeId() int32 {
	if o == nil || IsNil(o.OfficeId) {
		var ret int32
		return ret
	}
	return *o.OfficeId
}

// GetOfficeIdOk returns a tuple with the OfficeId field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ResponseExceptionalWkgDayResponse) GetOfficeIdOk() (*int32, bool) {
	if o == nil || IsNil(o.OfficeId) {
		return nil, false
	}
	return o.OfficeId, true
}

// HasOfficeId returns a boolean if a field has been set.
func (o *ResponseExceptionalWkgDayResponse) HasOfficeId() bool {
	if o != nil && !IsNil(o.OfficeId) {
		return true
	}

	return false
}

// SetOfficeId gets a reference to the given int32 and assigns it to the OfficeId field.
func (o *ResponseExceptionalWkgDayResponse) SetOfficeId(v int32) {
	o.OfficeId = &v
}

// GetOfficeName returns the OfficeName field value if set, zero value otherwise.
func (o *ResponseExceptionalWkgDayResponse) GetOfficeName() string {
	if o == nil || IsNil(o.OfficeName) {
		var ret string
		return ret
	}
	return *o.OfficeName
}

// GetOfficeNameOk returns a tuple with the OfficeName field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ResponseExceptionalWkgDayResponse) GetOfficeNameOk() (*string, bool) {
	if o == nil || IsNil(o.OfficeName) {
		return nil, false
	}
	return o.OfficeName, true
}

// HasOfficeName returns a boolean if a field has been set.
func (o *ResponseExceptionalWkgDayResponse) HasOfficeName() bool {
	if o != nil && !IsNil(o.OfficeName) {
		return true
	}

	return false
}

// SetOfficeName gets a reference to the given string and assigns it to the OfficeName field.
func (o *ResponseExceptionalWkgDayResponse) SetOfficeName(v string) {
	o.OfficeName = &v
}

// GetRemarks returns the Remarks field value if set, zero value otherwise.
func (o *ResponseExceptionalWkgDayResponse) GetRemarks() string {
	if o == nil || IsNil(o.Remarks) {
		var ret string
		return ret
	}
	return *o.Remarks
}

// GetRemarksOk returns a tuple with the Remarks field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ResponseExceptionalWkgDayResponse) GetRemarksOk() (*string, bool) {
	if o == nil || IsNil(o.Remarks) {
		return nil, false
	}
	return o.Remarks, true
}

// HasRemarks returns a boolean if a field has been set.
func (o *ResponseExceptionalWkgDayResponse) HasRemarks() bool {
	if o != nil && !IsNil(o.Remarks) {
		return true
	}

	return false
}

// SetRemarks gets a reference to the given string and assigns it to the Remarks field.
func (o *ResponseExceptionalWkgDayResponse) SetRemarks(v string) {
	o.Remarks = &v
}

func (o ResponseExceptionalWkgDayResponse) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o ResponseExceptionalWkgDayResponse) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.ApproverDate) {
		toSerialize["approver_date"] = o.ApproverDate
	}
	if !IsNil(o.ApproverId) {
		toSerialize["approver_id"] = o.ApproverId
	}
	if !IsNil(o.ExceptionalWkgDayDate) {
		toSerialize["exceptional_wkg_day_date"] = o.ExceptionalWkgDayDate
	}
	if !IsNil(o.OfficeId) {
		toSerialize["office_id"] = o.OfficeId
	}
	if !IsNil(o.OfficeName) {
		toSerialize["office_name"] = o.OfficeName
	}
	if !IsNil(o.Remarks) {
		toSerialize["remarks"] = o.Remarks
	}
	return toSerialize, nil
}

type NullableResponseExceptionalWkgDayResponse struct {
	value *ResponseExceptionalWkgDayResponse
	isSet bool
}

func (v NullableResponseExceptionalWkgDayResponse) Get() *ResponseExceptionalWkgDayResponse {
	return v.value
}

func (v *NullableResponseExceptionalWkgDayResponse) Set(val *ResponseExceptionalWkgDayResponse) {
	v.value = val
	v.isSet = true
}

func (v NullableResponseExceptionalWkgDayResponse) IsSet() bool {
	return v.isSet
}

func (v *NullableResponseExceptionalWkgDayResponse) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableResponseExceptionalWkgDayResponse(val *ResponseExceptionalWkgDayResponse) *NullableResponseExceptionalWkgDayResponse {
	return &NullableResponseExceptionalWkgDayResponse{value: val, isSet: true}
}

func (v NullableResponseExceptionalWkgDayResponse) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableResponseExceptionalWkgDayResponse) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


