/*
Treasury Management API

A comprehensive API for managing addresses, offering endpoints for creation, update, deletion, and retrieval of address data.

API version: 1.0
Contact: support_cept@indiapost.gov.in
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
)

// checks if the ResponseCreateAccountingTxnAPIResponse type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &ResponseCreateAccountingTxnAPIResponse{}

// ResponseCreateAccountingTxnAPIResponse struct for ResponseCreateAccountingTxnAPIResponse
type ResponseCreateAccountingTxnAPIResponse struct {
	Data *ResponseCreateAccountingDetails `json:"data,omitempty"`
	Message *string `json:"message,omitempty"`
	StatusCode *int32 `json:"status_code,omitempty"`
}

// NewResponseCreateAccountingTxnAPIResponse instantiates a new ResponseCreateAccountingTxnAPIResponse object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewResponseCreateAccountingTxnAPIResponse() *ResponseCreateAccountingTxnAPIResponse {
	this := ResponseCreateAccountingTxnAPIResponse{}
	return &this
}

// NewResponseCreateAccountingTxnAPIResponseWithDefaults instantiates a new ResponseCreateAccountingTxnAPIResponse object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewResponseCreateAccountingTxnAPIResponseWithDefaults() *ResponseCreateAccountingTxnAPIResponse {
	this := ResponseCreateAccountingTxnAPIResponse{}
	return &this
}

// GetData returns the Data field value if set, zero value otherwise.
func (o *ResponseCreateAccountingTxnAPIResponse) GetData() ResponseCreateAccountingDetails {
	if o == nil || IsNil(o.Data) {
		var ret ResponseCreateAccountingDetails
		return ret
	}
	return *o.Data
}

// GetDataOk returns a tuple with the Data field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ResponseCreateAccountingTxnAPIResponse) GetDataOk() (*ResponseCreateAccountingDetails, bool) {
	if o == nil || IsNil(o.Data) {
		return nil, false
	}
	return o.Data, true
}

// HasData returns a boolean if a field has been set.
func (o *ResponseCreateAccountingTxnAPIResponse) HasData() bool {
	if o != nil && !IsNil(o.Data) {
		return true
	}

	return false
}

// SetData gets a reference to the given ResponseCreateAccountingDetails and assigns it to the Data field.
func (o *ResponseCreateAccountingTxnAPIResponse) SetData(v ResponseCreateAccountingDetails) {
	o.Data = &v
}

// GetMessage returns the Message field value if set, zero value otherwise.
func (o *ResponseCreateAccountingTxnAPIResponse) GetMessage() string {
	if o == nil || IsNil(o.Message) {
		var ret string
		return ret
	}
	return *o.Message
}

// GetMessageOk returns a tuple with the Message field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ResponseCreateAccountingTxnAPIResponse) GetMessageOk() (*string, bool) {
	if o == nil || IsNil(o.Message) {
		return nil, false
	}
	return o.Message, true
}

// HasMessage returns a boolean if a field has been set.
func (o *ResponseCreateAccountingTxnAPIResponse) HasMessage() bool {
	if o != nil && !IsNil(o.Message) {
		return true
	}

	return false
}

// SetMessage gets a reference to the given string and assigns it to the Message field.
func (o *ResponseCreateAccountingTxnAPIResponse) SetMessage(v string) {
	o.Message = &v
}

// GetStatusCode returns the StatusCode field value if set, zero value otherwise.
func (o *ResponseCreateAccountingTxnAPIResponse) GetStatusCode() int32 {
	if o == nil || IsNil(o.StatusCode) {
		var ret int32
		return ret
	}
	return *o.StatusCode
}

// GetStatusCodeOk returns a tuple with the StatusCode field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ResponseCreateAccountingTxnAPIResponse) GetStatusCodeOk() (*int32, bool) {
	if o == nil || IsNil(o.StatusCode) {
		return nil, false
	}
	return o.StatusCode, true
}

// HasStatusCode returns a boolean if a field has been set.
func (o *ResponseCreateAccountingTxnAPIResponse) HasStatusCode() bool {
	if o != nil && !IsNil(o.StatusCode) {
		return true
	}

	return false
}

// SetStatusCode gets a reference to the given int32 and assigns it to the StatusCode field.
func (o *ResponseCreateAccountingTxnAPIResponse) SetStatusCode(v int32) {
	o.StatusCode = &v
}

func (o ResponseCreateAccountingTxnAPIResponse) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o ResponseCreateAccountingTxnAPIResponse) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Data) {
		toSerialize["data"] = o.Data
	}
	if !IsNil(o.Message) {
		toSerialize["message"] = o.Message
	}
	if !IsNil(o.StatusCode) {
		toSerialize["status_code"] = o.StatusCode
	}
	return toSerialize, nil
}

type NullableResponseCreateAccountingTxnAPIResponse struct {
	value *ResponseCreateAccountingTxnAPIResponse
	isSet bool
}

func (v NullableResponseCreateAccountingTxnAPIResponse) Get() *ResponseCreateAccountingTxnAPIResponse {
	return v.value
}

func (v *NullableResponseCreateAccountingTxnAPIResponse) Set(val *ResponseCreateAccountingTxnAPIResponse) {
	v.value = val
	v.isSet = true
}

func (v NullableResponseCreateAccountingTxnAPIResponse) IsSet() bool {
	return v.isSet
}

func (v *NullableResponseCreateAccountingTxnAPIResponse) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableResponseCreateAccountingTxnAPIResponse(val *ResponseCreateAccountingTxnAPIResponse) *NullableResponseCreateAccountingTxnAPIResponse {
	return &NullableResponseCreateAccountingTxnAPIResponse{value: val, isSet: true}
}

func (v NullableResponseCreateAccountingTxnAPIResponse) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableResponseCreateAccountingTxnAPIResponse) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


