/*
Treasury Management API

A comprehensive API for managing addresses, offering endpoints for creation, update, deletion, and retrieval of address data.

API version: 1.0
Contact: support_cept@indiapost.gov.in
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the HandlerCreateBankAddlCreditRequest type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &HandlerCreateBankAddlCreditRequest{}

// HandlerCreateBankAddlCreditRequest struct for HandlerCreateBankAddlCreditRequest
type HandlerCreateBankAddlCreditRequest struct {
	AddlCredit float32 `json:"addl_credit"`
	OfficeId string `json:"office_id"`
	Remarks string `json:"remarks"`
	UserId string `json:"user_id"`
}

type _HandlerCreateBankAddlCreditRequest HandlerCreateBankAddlCreditRequest

// NewHandlerCreateBankAddlCreditRequest instantiates a new HandlerCreateBankAddlCreditRequest object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewHandlerCreateBankAddlCreditRequest(addlCredit float32, officeId string, remarks string, userId string) *HandlerCreateBankAddlCreditRequest {
	this := HandlerCreateBankAddlCreditRequest{}
	this.AddlCredit = addlCredit
	this.OfficeId = officeId
	this.Remarks = remarks
	this.UserId = userId
	return &this
}

// NewHandlerCreateBankAddlCreditRequestWithDefaults instantiates a new HandlerCreateBankAddlCreditRequest object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewHandlerCreateBankAddlCreditRequestWithDefaults() *HandlerCreateBankAddlCreditRequest {
	this := HandlerCreateBankAddlCreditRequest{}
	return &this
}

// GetAddlCredit returns the AddlCredit field value
func (o *HandlerCreateBankAddlCreditRequest) GetAddlCredit() float32 {
	if o == nil {
		var ret float32
		return ret
	}

	return o.AddlCredit
}

// GetAddlCreditOk returns a tuple with the AddlCredit field value
// and a boolean to check if the value has been set.
func (o *HandlerCreateBankAddlCreditRequest) GetAddlCreditOk() (*float32, bool) {
	if o == nil {
		return nil, false
	}
	return &o.AddlCredit, true
}

// SetAddlCredit sets field value
func (o *HandlerCreateBankAddlCreditRequest) SetAddlCredit(v float32) {
	o.AddlCredit = v
}

// GetOfficeId returns the OfficeId field value
func (o *HandlerCreateBankAddlCreditRequest) GetOfficeId() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.OfficeId
}

// GetOfficeIdOk returns a tuple with the OfficeId field value
// and a boolean to check if the value has been set.
func (o *HandlerCreateBankAddlCreditRequest) GetOfficeIdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.OfficeId, true
}

// SetOfficeId sets field value
func (o *HandlerCreateBankAddlCreditRequest) SetOfficeId(v string) {
	o.OfficeId = v
}

// GetRemarks returns the Remarks field value
func (o *HandlerCreateBankAddlCreditRequest) GetRemarks() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Remarks
}

// GetRemarksOk returns a tuple with the Remarks field value
// and a boolean to check if the value has been set.
func (o *HandlerCreateBankAddlCreditRequest) GetRemarksOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Remarks, true
}

// SetRemarks sets field value
func (o *HandlerCreateBankAddlCreditRequest) SetRemarks(v string) {
	o.Remarks = v
}

// GetUserId returns the UserId field value
func (o *HandlerCreateBankAddlCreditRequest) GetUserId() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.UserId
}

// GetUserIdOk returns a tuple with the UserId field value
// and a boolean to check if the value has been set.
func (o *HandlerCreateBankAddlCreditRequest) GetUserIdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.UserId, true
}

// SetUserId sets field value
func (o *HandlerCreateBankAddlCreditRequest) SetUserId(v string) {
	o.UserId = v
}

func (o HandlerCreateBankAddlCreditRequest) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o HandlerCreateBankAddlCreditRequest) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["addl_credit"] = o.AddlCredit
	toSerialize["office_id"] = o.OfficeId
	toSerialize["remarks"] = o.Remarks
	toSerialize["user_id"] = o.UserId
	return toSerialize, nil
}

func (o *HandlerCreateBankAddlCreditRequest) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"addl_credit",
		"office_id",
		"remarks",
		"user_id",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varHandlerCreateBankAddlCreditRequest := _HandlerCreateBankAddlCreditRequest{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varHandlerCreateBankAddlCreditRequest)

	if err != nil {
		return err
	}

	*o = HandlerCreateBankAddlCreditRequest(varHandlerCreateBankAddlCreditRequest)

	return err
}

type NullableHandlerCreateBankAddlCreditRequest struct {
	value *HandlerCreateBankAddlCreditRequest
	isSet bool
}

func (v NullableHandlerCreateBankAddlCreditRequest) Get() *HandlerCreateBankAddlCreditRequest {
	return v.value
}

func (v *NullableHandlerCreateBankAddlCreditRequest) Set(val *HandlerCreateBankAddlCreditRequest) {
	v.value = val
	v.isSet = true
}

func (v NullableHandlerCreateBankAddlCreditRequest) IsSet() bool {
	return v.isSet
}

func (v *NullableHandlerCreateBankAddlCreditRequest) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableHandlerCreateBankAddlCreditRequest(val *HandlerCreateBankAddlCreditRequest) *NullableHandlerCreateBankAddlCreditRequest {
	return &NullableHandlerCreateBankAddlCreditRequest{value: val, isSet: true}
}

func (v NullableHandlerCreateBankAddlCreditRequest) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableHandlerCreateBankAddlCreditRequest) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


